### ISSUE TITLE
Measure slice and storage operations

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#1006]
We have `MeasuredSlice` and `MeasuredStorage` to track time for method calls of slice and storage. Now it prints results to logger. Let's change the implementation and submit these metrics to `Metrics` (we'll need to support histogram data type there: https://prometheus.io/docs/concepts/metric_types/#histogram). We are interested in these metrics:
 - [x] execution time of all operations of `Storage` (ms) [histogram]
 - [x] number of each operation in storage [counter]
 - [x] number of chunks in `save` and `load` `Storage` operations (see impl. below) [histogram]
 - [x] number of bytes in `save` and `load` `Storage` operations (see impl. below)
 - [x] number of `Slice` response method calls [counter]
 - [x] number of **request** body chunks per request (see impl. below) [histogram]
 - [x] number of bytes in **request** (see impl. below) [histogram]
 - [x] number of **response** body chunks per request (see impl. below) [histogram]
 - [x] number of bytes in **response** (see impl. below) [histogram]
 - [x] execution time of `Slice.response` method call (ms) [histogram]
 - [x] execution time of `Response.send` method calls (ms) [histogram]
 - [x] execution time of `Connection.accept` method calls (ms) [histogram]

*Implementation notes:*
 - To measure number of chunks in `Publisher` create `Subscriber` decorator with internal counter, increment counter on each `onNext` method call, complete counting on `onComplete`. Create `Publisher` decorator to override `subscribe` method and inject `Subscriber` from 1-st step to origin: `this.origin.subscribe(new MeasuredSubscriber(subscriber))`
 - TO measure number of bytes in `Publisher` create `Subscriber` decorator with internal counter, on each `onNext(ByteBuffer buf)` call: add `buf.remaining()` to counter, on complete publish the results. It could be the same class as from 1-st example.

https://github.com/prometheus/client_java

**Comment by baudoliver7** [comment]
@g4s8 Is it the right repository to work on this task or would it be [artipie/front](https://github.com/artipie/front) or other ?

**Comment by dgarus** [comment]
> @g4s8 Is it the right repository to work on this task or would it be [artipie/front](https://github.com/artipie/front) or other ?

Hi!
[artipie/front](https://github.com/artipie/front) will be deprecated soon.

**Comment by olenagerasimova** [comment]
done
