### ISSUE TITLE
integration-tests.yml:32-35: Fix integration test and...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#1013]
The puzzle `996-13b97ffa` from #996 has to be resolved: 

https://github.com/artipie/artipie/blob/bafd32223d9c09077025824bb1e467112e9270fb/.github/workflows/integration-tests.yml#L32-L35

The puzzle was created by Denis Garus on 10-Feb-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dgarus** [comment]
@g4s8 
double of #1009

**Comment by 0pdd** [comment]
The puzzle `996-13b97ffa` has disappeared from the source code, that's why I closed this issue.
