### ISSUE TITLE
Make bare metal installation a first class citizen

### ISSUE THREAD

**Issue by deknos** [artipie/artipie#1022]
Hello,
from a consultant and administator point of view your software is very interesting for companies who start out in the Cloud/Modern system landscape. But there is a problem: Many of them do not have much experience with Docker and/or Kubernetes and they hesitate saving their dependencies in a stack they do not understand or can manage, at least in the beginning of their journey.

Therefore it would be very good, at least for standard modules like maven, pip, docker, that they can install artipie directly on a (perhaps virtual) machine, without docker or kubernetes. 

Most of them will at a later point in time when their container-based workloads and systems are more mature migrate to a container-based installation, but at the start having a bare metal installation available and described in the documentation would be very important in my experience.

Thank you for considering it.

**Comment by olenagerasimova** [comment]
@deknos hello, thanks for the issue. Do I understand correctly, that by `bare metal installation` you mean running artipie `jar` with `java -jar`?

**Comment by deknos** [comment]
Hello and thanks for asking :)
in principal you are right, that "java -jar file" would be also okay, but:

* you only provide the source, not the file, so one have to build it. on the other side
* for artipie in the docker container i "just go to dockerhub" and pull the artipie container and/or adapt it.
* additionally a newcomer may not be sure, how to "add" an adapter as one would think that not all adapters are in your source and your jarfile will not look for adapters in the same directory, or?
* it's not clear from https://blog.artipie.com/ where the binary would fetch the configuration from.

it's possible that it is only a buildscript/documentation issue to make binary/bare metal installation a first class citizen, but from the README.md at the moment it's not clear how to do it.

**Comment by olenagerasimova** [comment]
@deknos 

> you only provide the source, not the file, so one have to build it

Artipie is a service, not a library, I do not see why add its jar into maven, we can only add jars into github releases

> additionally a newcomer may not be sure, how to "add" an adapter as one would think that not all adapters are in your source

all the adapters (all repository types Artipie support) are already included into Artipie, to use any supported repository you need to add corresponding [configuration file](https://github.com/artipie/artipie/wiki/Configuration-Repository) 

Please, note, that we also have [wiki](https://github.com/artipie/artipie/wiki/Configuration), it has more detailed description that readme. 

As for running Artipie as jar I think I'll extend wiki with the corresponding example and add jar into github release.

**Comment by deknos** [comment]
> all the adapters (all repository types Artipie support) are already included into Artipie, to use any supported repository you need to add corresponding [configuration file](https://github.com/artipie/artipie/wiki/Configuration-Repository)

okay, then i misunderststood that. 

> As for running Artipie as jar I think I'll extend wiki with the corresponding example and add jar into github release.

that would be perfect then! cool, thank you!

**Comment by olenagerasimova** [comment]
@deknos hello again, please, check [new section](https://github.com/artipie/artipie/wiki#how-to-start-artipie-service) in wiki about how to start Artipie jar file. The file is now available with every github [release](https://github.com/artipie/artipie/releases/tag/v0.23.10)

**Comment by deknos** [comment]
This is very nice, i will test it in a few hours!

**Comment by deknos** [comment]
sorry, forgot to reply, this is good for me!
