### ISSUE TITLE
Validate artipie's repositories readme files content

### ISSUE THREAD

**Issue by dgarus** [artipie/artipie#1031]
Repository - adapter:
 - check header (should be as maven-adapter has)
 - link to [roadmap](https://github.com/orgs/artipie/projects/3) 
 - link to telegram chat: https://t.me/artipie
 - maven dependency (if adapter has)
 - description of repository structure and link to the repository documentation the implementation is based on
 - description of SDK and examples how to use
 - description how to configure a client to use the repository
 - `how to contribute` section is exist and contains `Please read [contributing rules](https://github.com/artipie/artipie/blob/master/CONTRIBUTING.md)`
 -  add action for update license year

Artipie:
 - check header (should be as maven-adapter has)
 - link to telegram chat: https://t.me/artipie
 - link to [roadmap](https://github.com/orgs/artipie/projects/3)
 - check wiki content
 - how start
 - check all links
 - `how to contribute` section is exist and contains `Please read [contributing rules](https://github.com/artipie/artipie/blob/master/CONTRIBUTING.md)`
 - add action for update license year

code examples for copy-paste is [here](https://github.com/artipie/artipie/issues/1031#issuecomment-1163026586)

Repositories:
- [ ] artipie
    - [x] main config
    - [ ] repos
    - [x] repo perms
    - [x] creds
    - [x] storages
    - [x] metrix
- [x] asto (+)
- [x] front (+)
- [x] conan-adapter (+)
- [x] http (+)
- [x] rpm-adapter (Alena) (+)
- [x] npm-adapter (Alena) (+)
- [x] gem-adapter (Denis) (+)
- [x] git-adapter
- [x] p2-adapter
- [x] go-adapter
- [x] files-adapter (Denis) (+)
- [x] docker-adapter (Denis) (+)
- [x] helm-adapter (Denis)
- [x] pypi-adapter (pypi-example) (+)
- [x] maven-adapter (+)
- [x] http-client (+)
- [x] vertx-server (+)
- [x] nuget-adapter
- [x] conda-adapter (+)
- [x] cargo-adapter
- [x] debian-adapter (+)
- [x] composer-adapter (Denis)
- [x] benchmarks

**Comment by Swizbiz** [comment]
@artipie/members 
I think we should add this phrase to **How to contribute** 
> Please read [contributing rules](https://github.com/artipie/artipie/blob/master/CONTRIBUTING.md).

**Comment by Swizbiz** [comment]
@artipie/members 
I think we also have to bump year in license header to 2022

**Comment by dgarus** [comment]
> @artipie/members I think we also have to bump year in license header to 2022

We should do it easier, automatically.

**Comment by Swizbiz** [comment]
> > @artipie/members I think we also have to bump year in license header to 2022
> 
> We should do it easier, automatically. @Swizbiz could you please create an issue for this subject?

Created issue https://github.com/artipie/artipie/issues/1035

**Comment by Swizbiz** [comment]
README header example:
```
<a href="http://artipie.com"><img src="https://www.artipie.com/logo.svg" width="64px" height="64px"/></a>

[![Join our Telegramm group](https://img.shields.io/badge/Join%20us-Telegram-blue?&logo=telegram&?link=http://right&link=http://t.me/artipie)](http://t.me/artipie)

[![EO principles respected here](https://www.elegantobjects.org/badge.svg)](https://www.elegantobjects.org)
[![DevOps By Rultor.com](http://www.rultor.com/b/artipie/http-client)](http://www.rultor.com/p/artipie/http)
[![We recommend IntelliJ IDEA](https://www.elegantobjects.org/intellij-idea.svg)](https://www.jetbrains.com/idea/)

[![Javadoc](http://www.javadoc.io/badge/com.artipie/http-client.svg)](http://www.javadoc.io/doc/com.artipie/http-client)
[![License](https://img.shields.io/badge/license-MIT-green.svg)](https://github.com/artipie/http-client/blob/master/LICENSE.txt)
[![codecov](https://codecov.io/gh/artipie/http-client/branch/master/graph/badge.svg)](https://codecov.io/gh/artipie/http-client)
[![Hits-of-Code](https://hitsofcode.com/github/artipie/http-client)](https://hitsofcode.com/view/github/artipie/http-client)
[![Maven Central](https://img.shields.io/maven-central/v/com.artipie/http-client.svg)](https://maven-badges.herokuapp.com/maven-central/com.artipie/http-client)
[![PDD status](http://www.0pdd.com/svg?name=artipie/http-client)](http://www.0pdd.com/p?name=artipie/http-client)
```

Phrase about Telegram channel and roadmap:
```
If you have any question or suggestions, do not hesitate to [create an issue](https://github.com/artipie/http-client/issues/new) or contact us in
[Telegram](https://t.me/artipie).  
Artipie [roadmap](https://github.com/orgs/artipie/projects/3).
``` 

> **Warning**
> don`t forget change _http-client_ to your repository name

**Comment by 0pdd** [comment]
@dgarus the puzzle [#1083](https://github.com/artipie/artipie/issues/1083) is still not solved.

**Comment by 0pdd** [comment]
@dgarus the only puzzle [#1083](https://github.com/artipie/artipie/issues/1083) is solved here.
