### ISSUE TITLE
Fix smoke test CI script 

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#1037]
There are several problems with smoke test scripts and [examples](https://github.com/artipie/artipie/tree/master/examples) in Artipie:
1. Smoke tests CI script [fails](https://github.com/artipie/artipie/runs/6965556599?check_suite_focus=true) in spite of the fact that all tests are successful
2. In [examples](https://github.com/artipie/artipie/tree/master/examples#readme), docker and pypi are red, but actually the tests passed

**Comment by ChGen** [comment]
Also fixed issues in pdd-linter:
https://github.com/g4s8/pdd-action/pull/7
https://github.com/g4s8/pdd-action/pull/8
