### ISSUE TITLE
SliceFromConfig.java:45-46: We still don't have tests for...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#109]
The puzzle `90-c6a5c053` from #90 has to be resolved: 

https://github.com/artipie/artipie/blob/5c6f5c5013ba5534ec5cb8777685090280dd4104/src/main/java/com/artipie/SliceFromConfig.java#L45-L46

The puzzle was created by Hamdi Douss on 25-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@g4s8 could you please assign me?

**Comment by 0pdd** [comment]
The puzzle `90-c6a5c053` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#109` is not assigned, can't get performer
