### ISSUE TITLE
SliceFromConfig.java:65-67: This method still needs more...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#110]
The puzzle `90-277cd0cd` from #90 has to be resolved: 

https://github.com/artipie/artipie/blob/5c6f5c5013ba5534ec5cb8777685090280dd4104/src/main/java/com/artipie/SliceFromConfig.java#L65-L67

The puzzle was created by Hamdi Douss on 27-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#110](https://github.com/artipie/artipie/issues/110) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/40301464-abfb-4978-a644-a8967945d0a1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job
