### ISSUE TITLE
No configuration documentation for Go adapter

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#118]
Let's add configuration example for go adapter and available settings to wiki documentation at https://github.com/artipie/artipie/wiki/Examples

**Comment by 0crat** [comment]
The job [#118](https://github.com/artipie/artipie/issues/118) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/312dfd5b-8d6d-419f-8776-77f37c587cee); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@g4s8 please check https://github.com/artipie/artipie/wiki/Examples#local-go-registry

**Comment by g4s8** [comment]
@olenagerasimova can you please add some details about directory layout for this repository? Is it the same as local repository? E.g. can I put some package like in local repository to `src/github.com/username/package` ?

**Comment by olenagerasimova** [comment]
@g4s8 added, take a look please

**Comment by g4s8** [comment]
@olenagerasimova thanks

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by olenagerasimova** [comment]
@g4s8 please, could you ask 0crat to close the order? This issue is still in my agenda

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
