### ISSUE TITLE
Pie.java:49-52: Create a unit test for 404 response....

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#120]
The puzzle `74-e630ca71` from #74 has to be resolved: 

https://github.com/artipie/artipie/blob/2ef2028f29ee2b5fa4b794091c9ed57408373f13/src/main/java/com/artipie/Pie.java#L49-L52

The puzzle was created by @g4s8 on 08-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#120](https://github.com/artipie/artipie/issues/120) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/fc01d714-bc08-4bc7-95d8-37eec28aeaa7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/120#issuecomment-626580757))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#120](https://github.com/artipie/artipie/issues/120), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#120](https://github.com/artipie/artipie/issues/120) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1fd58da6-b0ee-43bb-9161-19d238f5edd3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #144

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status  ([here](https://github.com/artipie/artipie/issues/120#issuecomment-634601304))

@victornoel This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#120](https://github.com/artipie/artipie/issues/120) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fartipie%23120%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@g4s8 even though the PR was merged and the todo was removed, 0pdd didnt' close the issue, also, can you re-assign me on it following the bug we talked about in telegram?

**Comment by g4s8** [comment]
@0crat assign @victornoel

**Comment by 0crat** [comment]
> @0crat assign @victornoel  ([here](https://github.com/artipie/artipie/issues/120#issuecomment-635169430))

@g4s8 The job [#120](https://github.com/artipie/artipie/issues/120) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/dfb276fe-89b4-4d73-a384-ac7045989316); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `74-e630ca71` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by sereshqua** [comment]
@0crat quality good
