### ISSUE TITLE
Release Artifact on Central

### ISSUE THREAD

**Issue by ChGen** [artipie/artipie#1206]
### Discussed in https://github.com/artipie/artipie/discussions/1205

<div type='discussions-op-text'>

<sup>Originally posted by **khmarbaise** December  3, 2022</sup>
Hi, is there a particular reason why the current release artifact is not available via central repository?</div>

Check and release Aripie artifacts to the central repository

**Comment by olenagerasimova** [comment]
@ChGen [take a look](https://github.com/artipie/artipie/actions/runs/3740065456/jobs/6347995933#step:9:50478): let's disable profile trying to push docker image and also skip all tests with `-DskipTests` optiop

**Comment by ChGen** [comment]
@olenagerasimova , ok

**Comment by olenagerasimova** [comment]
@ChGen deploy [failed](https://github.com/artipie/artipie/actions/runs/3740930067/jobs/6349885341#step:9:49672), you need to add `--add-opens` options as on [this line](https://github.com/artipie/maven-adapter/blob/21529575363cd452e3a3cab8d4ebc0fa7eab3eb4/.github/workflows/release.yml#L56) in maven release

**Comment by ChGen** [comment]
artipie v0.28.0 artifacts now available in Central:
https://mvnrepository.com/artifact/com.artipie/artipie
https://repo1.maven.org/maven2/com/artipie/artipie/v0.28.0/

**Comment by olenagerasimova** [comment]
@ChGen sorry, but it seems we can improve some things regarding this task:
1) as we are releasing jar with dependencies to maven, there is no need to duplicate it into [release pages](https://github.com/artipie/artipie/releases)
2) if we do the first point, we need to change [this section](https://github.com/artipie/artipie/wiki#how-to-start-artipie-service-with-a-maven-proxy-repository) in wiki to suggest getting jar from maven instead from the release page

**Comment by ChGen** [comment]
@olenagerasimova , ok

**Comment by olenagerasimova** [comment]
all done
