### ISSUE TITLE
java.nio.file.NoSuchFileException while requesting an artifact

### ISSUE THREAD

**Issue by stepanov-dmitry** [artipie/artipie#125]
I'm just a newcomer of this project, that's why I've just read white-paper and were going through `README.md` file, [Configuration](https://github.com/artipie/artipie/wiki/Configuration) and [Examples](https://github.com/artipie/artipie/wiki/Examples) and encountered with the following exception:
`Caused by: java.nio.file.NoSuchFileException: /var/artipie/repo/myrep.yaml`.

OS details:
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

Steps to reproduce the issue:
1. `sudo -s`
2. Install docker.
3. `mkdir /var/artipie/`
4. `cd /var/artipie/`
5. `mkdir repo`
6. `vi repo/myrepo.yml` (the name of file was taken from [Examples](https://github.com/artipie/artipie/wiki/Examples))
7. Insert the following config (taken from  [Examples](https://github.com/artipie/artipie/wiki/Examples)):
```
repo:
  type: rpm
  storage:
    type: fs
    path: /var/artipie/storage
```
8. `docker run -v $PWD:/var/artipie -p 80:80 artipie/artipie:0.1.2` (taken from README.md)
9. `curl -X PUT localhost/myrep/libsqlite3.so`. The output of this request is below: 
```
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /var/artipie/repo/myrep.yaml
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /var/artipie/repo/myrep.yaml
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /var/artipie/repo/myrep.yaml
        at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
        at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
        at io.reactivex.Single.blockingGet(Single.java:2835)
        at com.artipie.asto.fs.FileStorage.lambda$value$12(FileStorage.java:163)
        ... 2 more
Caused by: java.nio.file.NoSuchFileException: /var/artipie/repo/myrep.yaml
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source)
        at java.base/java.nio.file.Files.readAttributes(Unknown Source)
        at java.base/java.nio.file.Files.size(Unknown Source)
        at com.artipie.asto.fs.RxFile.lambda$size$9(RxFile.java:162)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.Single.blockingGet(Single.java:2834)
        ... 3 more
```

The point here, which confuses, is that the server is trying to point to `/var/artipie/repo/myrep.yaml` while my config file name is `/var/artipie/repo/myrepo.yml` according to [Examples](https://github.com/artipie/artipie/wiki/Examples) page. 

Looks like something is missing in README.md to properly start using the tool.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@stepanov-dmitry thanks for the report. It seems you've created a repository named `myrepo`:
 > vi repo/myrepo.yml (the name of file was taken from Examples)

But requesting it as `myrep` (without `o`), this is why it fails.
We already have improved the HTTP response, now it should return `404` error instead of `500` with stacktrace, see: https://github.com/artipie/artipie/issues/74

**Comment by stepanov-dmitry** [comment]
Yes, one of the reason of this issue is due to wrong repo name, but I've encountered with it, since data in examples is not consistent. But there is another reason why I've encountered with this issue again is due to the file name `/var/artipie/repo/myrep.yml`, which is mentioned on [Examples](https://github.com/artipie/artipie/wiki/Examples) page:

![image](https://user-images.githubusercontent.com/41523193/81753276-1aa4ec80-94bc-11ea-94bd-607fb0e317db.png)


So, since data on [Examples](https://github.com/artipie/artipie/wiki/Examples) page is not consistent, I really recommend to update that page and apply my comments below, because it might confuse a user of this tool: 

 
![image](https://user-images.githubusercontent.com/41523193/81753439-766f7580-94bc-11ea-8e4e-9c52799ed66d.png)

**Comment by stepanov-dmitry** [comment]
Regarding the response code, I'm still getting 500, since for now the file `README.md` contains command for `0.1.2` release and I was using the same version as in the example:

![image](https://user-images.githubusercontent.com/41523193/81753738-204f0200-94bd-11ea-9b22-a65821b1b6ff.png)

, but looks like the error code was changed in one of the newer versions. If so, I'd recommend to update the command example as well.

**Comment by 0crat** [comment]
The job [#125](https://github.com/artipie/artipie/issues/125) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1e22f6c9-e68f-410d-9b69-3f94bf04e10c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by genryxy** [comment]
@stepanov-dmitry Hi! Could you please try the latest version [`v0.22`](https://github.com/artipie/artipie/releases/tag/v0.22)
`docker run --rm --name artipie -p 8080:8080 --user=artipie:artipie artipie/artipie:v0.22` (according to [readme](https://github.com/artipie/artipie#quickstart))
Info about configuration files could be find [here](https://github.com/artipie/artipie/wiki/Configuration)
After running command above you need to open `http://localhost:8080/dashboard/artipie` and create a new repo.

**Comment by genryxy** [comment]
@stepanov-dmitry Hi! Do you have any updates about this issue?

**Comment by genryxy** [comment]
@g4s8 this issue looks like invalid now
