### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by 1oglop1** [artipie/artipie#1259]
Hi, I just learned about this project and it looks like a promising alternative to Nexus/Artifactory.

I have a few questions:

### 1 Authentication
It looks like different repository types require different authentication types. 

examples: 
`pypi` - username/password - https://github.com/artipie/artipie/wiki/pypi
`npm` - oauth token - https://github.com/artipie/artipie/wiki/npm

And for example, there are no settings examples for `nuget` https://github.com/artipie/artipie/wiki/nuget.

Is there any plan to unify the authentication somehow? 
E.g. With Gitlab there is a universal username `__token__` together with PAT.

### 2 hexpm/config

My second question is about private HexPM https://github.com/artipie/artipie/wiki/hexpm 
Wiki suggest disabling the security which is probably not a good idea. Is there any reason why is that?

```
defp hex() do
    [
      unsafe_registry: true,
      no_verify_repo_origin: true
    ]
  end
  ```

**Comment by olenagerasimova** [comment]
@1oglop1 hi, sorry for the delay.
1. Authentication type for different repositories depends on the repository client requirements. Latest npm version works with tokens only, so we HAVE to use tokens. Pypi works with username/password, so we HAVE to work in the same way.
2. If your artipie instance is running behind https (you can set it up with nginx for example) there is no need to disable security.

**Comment by 1oglop1** [comment]
Thanks @olenagerasimova that's great news!

**Comment by voltone** [comment]
> If your artipie instance is running behind https (you can set it up with nginx for example) there is no need to disable security.

HTTPS is a different issue. The two flags mentioned in the wiki disable the signature verification on the package registry, which is necessary because `hexpm-adapter` sets the signature to an empty string (https://github.com/artipie/hexpm-adapter/blob/master/src/main/java/com/artipie/hex/http/UploadSlice.java#L320). It will remain necessary to disable security on the client side until `hexpm-adapter` allows a key pair to be provisioned and calculates and inserts a valid signature during package publication.

**Comment by olenagerasimova** [comment]
@Swizbiz may be you could add some comments or implementation notes?

**Comment by ChGen** [comment]
@voltone, @oglop1 do you want feature, like to be able to assign the single set of login/password/PAT values for all repos in the single Artipie instance?

**Comment by 1oglop1** [comment]
@ChGen At this point, we are talking about 2 different topics in this issue. 
I think it would be a good idea to create separate issues to avoid confusion.

1. Unified - Login/PAT interface 
   It would be great if Artipie abstracted/unified the login complexity for package managers.
   The goal would be to eliminate an extra step, like calling `curl` to get an NPM token.
   
   I realize it may be easier said than done, but here 
   What Gitlab does:
    * PyPI - username for everyone is `__token__` and password is Gitlab PAT: `glpat-..............`
    * NPM - NPM token is GitlabPAT directly
   What Nexus does: 
    * PyPI - username & password
    * NPM - basic auth, token = base64 encoded username:password
   
   Also, I just noticed that NPM CLI offers a switch `--auth-type=legacy` which enables basic auth.
   https://docs.npmjs.com/cli/v9/commands/npm-adduser#auth-type
   

2. HexPM issue 
https://github.com/artipie/hexpm-adapter/blob/a45c0100d4b35657bf6301270d6151904605bc4e/tasks.md?plain=1#L1

https://github.com/artipie/hexpm-adapter/blob/a45c0100d4b35657bf6301270d6151904605bc4e/src/main/java/com/artipie/hex/http/UploadSlice.java#L320

**Comment by 1oglop1** [comment]
@ChGen shall we keep this issue open or has that been broken down into feature requests?

**Comment by ChGen** [comment]
@1oglop1 , since it consist of at least two different issues, it would be better to create separate issues for each specific problem, so it could be discussed separately.

**Comment by 1oglop1** [comment]
Closing this in favour of #1294 and artipie/hexpm-adapter#75
