### ISSUE TITLE
Switch http error code from 500 to 404 if no resource found

### ISSUE THREAD

**Issue by artemlazarev** [artipie/artipie#126]
If we will try to get resource from unconfigured storage, we will receive http 500. But according http logic we must recieve http 404.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@artemlazarev it's a duplicate of https://github.com/artipie/artipie/issues/74
