### ISSUE TITLE
Support of scripting

### ISSUE THREAD

**Issue by andpopov** [artipie/artipie#1277]
Artipie should provide a support of custom logic by means of scripts.

- Provide scripting support. 
   Consider integration of JVM scripting languages as Groovy, MVEL, JRuby and Jython by means of Java Scripting Engine API (see JSR 223).
- Expose Artipie objects to scripting environment (like access to storages, repositories etc)
- Provide useful Artipie API to scripting environment (like access to artifacts and set of actions over artifacts)
- Provide means to run custom scripts by scheduling
- Provides means to run custom scripts on Artipie events (line changes in storage or Artipie objects changing)

**Comment by ChGen** [comment]
Status:
Working branch is https://github.com/andpopov/artipie/tree/scheduled_scripts
Branch could be compiled and tested.
In that branch following parts are complete:
1. Provide scripting support.
Consider integration of JVM scripting languages as Groovy, MVEL, JRuby and Jython by means of Java Scripting Engine API (see JSR 223).
2. Provide means to run custom scripts by scheduling

**Comment by ChGen** [comment]
Status:
Pull request is in review: 
https://github.com/artipie/artipie/pull/1304

**Comment by ChGen** [comment]
Completed.
