### ISSUE TITLE
What is infallible_wright image name? 

### ISSUE THREAD

**Issue by jeffzhu503** [artipie/artipie#128]
I ran the docker command in the Mac Pro using the example from README.  I see infallible_wright as the running docker by artipie.  Where does this name come from?  Shall we change to something called artipie instead of infalliable_wright?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@jeffzhu503 Docker generates random name for running container, it's not related to Artipie. You can specify container name as `--name` option, e.g. `docker run --name="my-container-name" <image>`, see https://docs.docker.com/engine/reference/run/#name---name

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#128` is not assigned, can't get performer

**Comment by jeffzhu503** [comment]
Got it.  Please update README by giving the --name="Artipie".  Thanks.
