### ISSUE TITLE
Default roles

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#1289]
As we discussed I'm suggesting to implement default roles depending on auth type. Here is suggested files structure for `artipie` policy type:
```
├── roles
│   ├── default
│   │   ├──  keycloack.yaml
│   │   ├──  env.yml
│   │   ├──  artipie.yaml
│   ├── java-dev.yaml
│   ├── admin.yaml
│   ├── ...
├── users
│   ├── david.yaml
│   ├── jane.yaml
│   ├── ...
```
Subfolder `default` in `roles` folder will contain yamls with default roles permissions for auth type. The name of the file must match auth type, in java code, we store this auth type in `context` field of `AuthUser` object and thus, we know what default role permissions to check. 
Format of this default roles yaml is the same as the format of yaml with usual role.

**Comment by olenagerasimova** [comment]
@dgarus please, check. What do you think?

**Comment by dgarus** [comment]
> @dgarus please, check. What do you think?

Hi! It looks like a suitable solution.
