### ISSUE TITLE
Quick start section is missing from README

### ISSUE THREAD

**Issue by jeffzhu503** [artipie/artipie#129]
We have a section "Run Artipie as a Docker image", which is a good beginning of Quick Start.  
However, what shall users do next?  How can they start using Artipie now in the local machine running as a docker?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.1`

**Comment by yegor256** [comment]
@jeffzhu503 take a look at README now. Better?

**Comment by g4s8** [comment]
@jeffzhu503 I suppose it was fixed by @yegor256

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#129` is not assigned, can't get performer
