### ISSUE TITLE
Failed to read/parse file 'roles/default/artipie'

### ISSUE THREAD

**Issue by fink-andreas** [artipie/artipie#1318]
Installed latest artipie via docker.

```
docker login --username artipie localhost:8080
```

Trying to push an image:
```
docker push localhost:8080/my-docker/myfirstimage
```

Error message:

```
artipie    | [Thread-104] INFO com.artipie.settings.cache.CachedUsers - Successfully authenticated 'artipie' user via CachedUsers(size=3),origin=Joined([Joined([AuthFromEnv(),GithubAuth()]),AuthFromStorage])
artipie    | [Thread-104] ERROR com.artipie.asto.ValueNotFoundException - Failed to read/parse file 'roles/default/artipie'
artipie    | [Thread-104] INFO com.artipie.http.MainSlice - << FORBIDDEN
artipie    | Content-Length: 85
artipie    | Content-Type: application/json; charset=utf-8

```

I would expect there is no need for default role for artipie user, as stated in https://github.com/artipie/artipie/wiki/Configuration-Policy#default-permissions _"Default roles permissions files are not required."_

**Comment by olenagerasimova** [comment]
yes, there is no need for default roles. Example configuration allows `artipie` user to read from any repo, push into docker is not allowed by default. You can grant it, read [this](https://github.com/artipie/artipie/wiki/Configuration-Policy#docker-adapter-permissions)
