### ISSUE TITLE
Artipie is too slow

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#132]
Artipie files operation are too slow: write of single small file may be processed for about 3-5 seconds. Investigate the reason and fix it.

The subtask is: https://github.com/artipie/asto/issues/171

**Comment by 0crat** [comment]
The job [#132](https://github.com/artipie/artipie/issues/132) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/fd037ac9-9d4e-445d-b7eb-07d9b8782814); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
Fixed

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#132` is not assigned, can't get performer
