### ISSUE TITLE
Java LinkageErrors reported for `front` docker image deployed via docker-compose

### ISSUE THREAD

**Issue by CJLove** [artipie/artipie#1360]
Hi! 

Was taking a look at artipie as it appears to meet a lot of my needs for my homelab dev environment. I'm using the `docker-compose.yaml` from the repo. The `latest` for the `front` image appears to be tag v0.2.2 per https://hub.docker.com/r/artipie/front/tags.

Logs from the `front` container are:
```
front      | Error: LinkageError occurred while loading main class com.artipie.front.Service
front      | 	java.lang.UnsupportedClassVersionError: com/artipie/front/Service has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
```

It appears the `artipie` container deployed successfully, so this issue is limited to the `front` image.

Host environment is Fedora 38 with Docker Engine v24.0.7. Please advise if there's any more information I can provide to help.

Thanks!

**Comment by CJLove** [comment]
Just to follow up, switching to tag v0.2.1 works fine.

**Comment by dgarus** [comment]
@CJLove 
thanks for the issue!
