### ISSUE TITLE
S3 storage bug

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#138]
S3 storage is not working because of the bug: https://github.com/artipie/asto/issues/163
Fix the bug in asto module and update the dependency

**Comment by 0crat** [comment]
The job [#138](https://github.com/artipie/artipie/issues/138) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d99354da-3094-4471-b637-49de8c3d6df8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.2.2`

**Comment by g4s8** [comment]
Fixed by artipie/asto#163
Updated in #139 
Released `0.2.2`

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
