### ISSUE TITLE
Bug: PyPI repository upload to S3 storage is broken

### ISSUE THREAD

**Issue by EDF-MarcellO** [artipie/artipie#1383]
I'm running Artipie using AWS App Runner in a containerized deployment with S3 storage specified. When I want to upload PyPI packages to the PyPI repository hosted on Artipie, I am greeted with following error:

Upload command:
python3 -m twine upload --repository-url https://domain.region.awsapprunner.com/pypi -u username -p password --verbose numpy-1.26.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
(package available from: https://pypi.org/project/numpy/#files)

Response:
INFO Response from https://domain.region.awsapprunner.com/pypi:                   
         400 Bad Request                                                                     
INFO Bad request                                                                         
         software.amazon.awssdk.services.s3.model.S3Exception: You must provide the          
         Content-Length HTTP header. (Service: S3, Status Code: 411, Request ID:             
         SomeRandomID, Extended Request ID: AnotherRandomID)

What I would like to see:
Successful upload of wheel file to Artipie PyPI repository.

N.B.: Placing the wheel file into the dist folder and running an updated command (to upload all files in dist folder, dist/*) yields the same results.

Repository configuration yaml file:
repo:
  type: pypi
  storage:
    type: s3
    bucket: my-s3-bucket
    region: my-s3-region
    
(obviously, some domain names have been redacted for security purposes, happy to share details privately)

**Comment by bade02r** [comment]
Hi @ChGen,  is this fix released with in the latest version? if not, when are you planning to release?

**Comment by bade02r** [comment]
@ChGen , thanks for the fix, would you mind to release a minor version with the latest fixes?

**Comment by ChGen** [comment]
@bade02r , published `artipie/artipie:v0.30.13`. Feedback is appreciated :)

**Comment by ChGen** [comment]
Should be fixed in `artipie/artipie:v0.30.14`. Please, reopen with fresh logs in case of errors.
