### ISSUE TITLE
Integrate authorization mechanism to supported adapters

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#145]
Add existing authorization mechanisms to all supported adapters:
 - [x] Files
 - [x] Maven
 - [ ] Docker
 - [x] RPM
 - [x] Npm
 - [ ] Gem
 - [ ] Helm
 - [ ] PHP
 - [x] Nuget
 - [ ] Go
 - [x] PyPi

**Comment by 0crat** [comment]
The job [#145](https://github.com/artipie/artipie/issues/145) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/031d6227-1c7e-499b-8bf5-52b310653e96); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
Closing as done
