### ISSUE TITLE
Uploading is broken (Error 401 Unauthorized with token, with password or with anonymous user)

### ISSUE THREAD

**Issue by Karina5005** [artipie/artipie#1466]
Step to reproduce:

1. Run artipie on host:
a. Change configuration:
    /var/artipie/security/users/test_user.yml

        type: plain
        pass: qwerty
        enabled: true
        roles:
          - uploader
          - reader
          - api-admin
   
      /var/artipie/security/roles/uploader.yml

        enabled: true
        permissions:
          adapter_basic_permissions:
            "*":
              - read
              - write
      Other files was not changed
      b. Run docker container: `docker run -it -p 8080:8080 -p 8086:8086 -d -v artipie:/var/artipie artipie/artipie:latest`
2. Try to upload file from other machine
a. Generate token for test_user/qwerty
b.
 **Run** `curl -v --noproxy '*' -H 'Authorization: Bearer TOKEN' -X PUT -d 'Hello world!' -u test_user:qwerty http://HOST_IP:8080/my-bin/test.txt`
    **Result**: 401 Unauthorized
    **Artipie logs**:
``` [INFO] 2024-07-16 09:42:22,626 vert.x-eventloop-thread-0 com.artipie.http.MainSlice - << UNAUTHORIZED```
c. 
**Run** `curl -v --noproxy '*' -X PUT -d 'Hello world!' http://HOST_IP:8080/my-bin/test.txt`
    **Result**: 401 Unauthorized
    **Artipie logs**: 

        [ERROR] 2024-07-16 11:36:44,094 vert.x-eventloop-thread-0 security - Failed to read or parse file 'users/anonymous'
        [ERROR] 2024-07-16 11:36:44,095 vert.x-eventloop-thread-0 security - Failed to read/parse file 'roles/default/unknown'
        [INFO] 2024-07-16 11:36:44,095 vert.x-eventloop-thread-0 com.artipie.http.slice.TrimPathSlice - << UNAUTHORIZED

**Comment by ChGen** [comment]
@Karina5005 , I've prepared test configurations for Artipie files adapter. Please check if it works for you.
1. Without auth: https://github.com/ChGen/artipie-test-setups/tree/main/files-no-auth
2. With auth: https://github.com/ChGen/artipie-test-setups/tree/main/files-with-auth

**Comment by Karina5005** [comment]
> @Karina5005 , I've prepared test configurations for Artipie files adapter. Please check if it works for you.
> 
> 1. Without auth: https://github.com/ChGen/artipie-test-setups/tree/main/files-no-auth
> 2. With auth: https://github.com/ChGen/artipie-test-setups/tree/main/files-with-auth

It works, thanks!
