### ISSUE TITLE
No Ruby gem documentation in the readme

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#147]
Add documentation similar to other repository types how to configure gem repository in artipie and how to use from gem CLI tool.

**Comment by 0crat** [comment]
The job [#147](https://github.com/artipie/artipie/issues/147) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/5391e346-6f21-46a1-b826-29e1a6d3903f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by Sammers21** [comment]
@g4s8, there is no such thing as gem CLI tool

**Comment by g4s8** [comment]
> @g4s8, there is no such thing as gem CLI tool

@Sammers21 what's about `gem`? I suppose it's `gem` CLI tool.

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @sammers21[/z](https://www.0crat.com/u/sammers21), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
