### ISSUE TITLE
Simple authentication via environment variables

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#148]
Add a simplest one user authentication via environment variables:
 - `ARTIPIE_USER_NAME` for user name
 - `ARTIPIE_USER_PASS` for password

Such configuration must have the highest priority and should provide `Authentication` mechanism with single user with such credentials.

Simplified version of #146

**Comment by 0crat** [comment]
The job [#148](https://github.com/artipie/artipie/issues/148) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/80e74158-9ffe-4e32-8f5d-9ec30a833e35); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.3`

**Comment by g4s8** [comment]
Done

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#148` is not assigned, can't get performer
