### ISSUE TITLE
Repository was not found

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#153]
I have configured gem repo in the following way:
`gem.yml`
```
repo:
  type: gem
  storage:
    type: fs
    path: /Users/sammers/artipie/data
```

And then I tried to push a gem:
```
$ GEM_HOST_API_KEY=123 gem push builder-3.2.4.gem --host http://localhost:8080/gem
Pushing gem to http://localhost:8080/gem...
Repository 'gem' was not found
```

Push failed with `Repository 'gem' was not found`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@Sammers21 `gem.yml` is not correct, use `gem.yaml` instead

**Comment by Sammers21** [comment]
@g4s8, `gem.yml` is correct, but artipie for some reasons could not recognize it.

**Comment by g4s8** [comment]
@Sammers21 right now it's looking for `{repo}.yaml` file with configuration in repository config location. This is why `gem.yml` is not correct

**Comment by Sammers21** [comment]
@g4s8, `.yml` is a correct extension for YAML content and it is a bug that artipie could not recognize that.
