### ISSUE TITLE
Provide a status for each example in the README

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#154]
In the README file, you can found a dozen configurations and usage examples. In order to double-check that those examples are valid and actually works, I suggest creating a GitHub action and provide a status for each example.  

Progress:
 - [x] - Binary
 - [x] - Maven
 - [ ] - RPM
 - [x] - Docker
 - [x] - Helm
 - [x] - NPM
 - [ ] - Composer
 - [ ] - NuGet
 - [x] - Gem
 - [x] - Pypi
 - [ ] - Go

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#154](https://github.com/artipie/artipie/issues/154) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/9852e0bb-4f19-40e0-a72c-1417ed44c6f4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@Sammers21 one more question: how would you prove that the repository is actually works? The're can be multiple thing in one repository to verify. E.g. docker push works, docker pull works, docker tag, etc. What do you think about using Cucumber tests to write scenarios for each repository?

**Comment by g4s8** [comment]
@Sammers21 what's the progress of this job?

**Comment by Sammers21** [comment]
@g4s8, no progress

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#154` is not assigned, can't get performer
