### ISSUE TITLE
Benchmarks reporting

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#158]
Report benchmark results to GitHub pages

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@771b26b8-67e1-41d2-9b59-49db76911c64, thread: PQ-CT2E6TK9B
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.staff.bans.ban_github_reporter
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.lang.OutOfMemoryError: unable to create new native thread
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.53.14](https://github.com/zerocracy/farm): CID: [06f232e6-0976-4cbe-be9e-f067ed5b6aba](https://www.0crat.com/footprint/CT2E6TK9B/06f232e6-0976-4cbe-be9e-f067ed5b6aba), Type: "Job was added to WBS"

**Comment by g4s8** [comment]
Done

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#158` is not assigned, can't get performer
