### ISSUE TITLE
Don't require authorization when no permission block in repo config

### ISSUE THREAD

**Issue by brastak** [artipie/artipie#169]
We need to distinguish 2 situations:
- there is permissions section in repo config, but current user is not in
- there is no permissions section at all

Now both situation causes 403 error

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@brastak yes, good point

**Comment by 0crat** [comment]
The job [#169](https://github.com/artipie/artipie/issues/169) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/27225564-68d4-43aa-b9de-14a2162c23df); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#169](https://github.com/artipie/artipie/issues/169) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d8dd28fa-cca8-40b4-9a55-2c9b76a6d57c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@g4s8 hm, I'm not sure I see why we should distinguish these situations as outcome is the same: no actions are allowed to current user and return 403 in this case seems reasonable. If we still want to this, please, specify what we should do if `permissions` section is absent. Throw an exception?

**Comment by olenagerasimova** [comment]
@g4s8 hm, maybe we can add one more `credentials` type `public` for this case? This will mean that any user get authorized, then allowing anybody `\*` all `\*` actions should work.

**Comment by g4s8** [comment]
> @g4s8 hm, maybe we can add one more `credentials` type `public` for this case? This will mean that any user get authorized, then allowing anybody `\*` all `\*` actions should work.

@olenagerasimova I don't think it's a good idea. The common scenario could be: few peoples has upload access for repository, but downloads are public and any user without authentication can download it (like Maven central for instance)

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by olenagerasimova** [comment]
@g4s8 can we close this?

**Comment by g4s8** [comment]
@olenagerasimova thanks
