### ISSUE TITLE
Turn on authentication for NPM adapter

### ISSUE THREAD

**Issue by brastak** [artipie/artipie#170]

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@brastak can you specify please what kind of permissions npm adapter may handle? I suppose it's `publish` and `install`?

**Comment by brastak** [comment]
@g4s8 I suppose we can use `upload` and `download` it has  almost the same semantic

**Comment by 0crat** [comment]
You @brastak[/z](https://www.0crat.com/u/brastak) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by g4s8** [comment]
> @g4s8 I suppose we can use `upload` and `download` it has almost the same semantic

@brastak agree, it looks better to have same names for repositories where possible.

**Comment by g4s8** [comment]
@rultor release, tag=`0.3.3`

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#170` is not assigned, can't get performer
