### ISSUE TITLE
Integrate Docker repository

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#172]
Add Docker repository support and usage example to documentation

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#172` is not assigned, can't get performer
