### ISSUE TITLE
Do not build assembly jar-with-dependencies by default

### ISSUE THREAD

**Issue by victornoel** [artipie/artipie#175]
Running `mvn verify -Pqulice` is extremely long because of the task `make-assembly`.

It shouldn't be enabled in a normal build but only via a profile.

I suppose the CI should take that into account also (depending on where this jar is needed).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat assign @marceloamadeu

**Comment by 0crat** [comment]
> @0crat assign @marceloamadeu ([here](https://github.com/artipie/artipie/issues/175#issuecomment-634655227))

@g4s8 The job [#175](https://github.com/artipie/artipie/issues/175) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/e098cb96-37ee-4eb5-9b46-89346da79455); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#175](https://github.com/artipie/artipie/issues/175), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by marceloamadeu** [comment]
@g4s8 please close ... tks

**Comment by victornoel** [comment]
@marceloamadeu I will close, but do you realise you have been unassigned from this job? Ask @g4s8 to add you again before I close, so that you can get paid for it…

**Comment by marceloamadeu** [comment]
@victornoel Yes, I realize that it is not assigned to me... 
@g4s8 Is it possible to add me again before closing?

Tks

**Comment by victornoel** [comment]
@marceloamadeu I usually tell 0crat to wait once I have made a PR for a ticket, so that this situation does not happen :) For example: https://github.com/artipie/artipie/issues/120#issuecomment-629658274

**Comment by g4s8** [comment]
@0crat assign @marceloamadeu

**Comment by 0crat** [comment]
> @0crat assign @marceloamadeu  ([here](https://github.com/artipie/artipie/issues/175#issuecomment-640674564))

@g4s8 The job [#175](https://github.com/artipie/artipie/issues/175) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/399bc605-8b09-4315-9fb5-d404278c5b56); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@g4s8 @marceloamadeu :+1:

**Comment by marceloamadeu** [comment]
@victornoel @g4s8 Tks :+1:

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ee0a5bef-126a-4a0b-9365-89a9ee5abc02, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/artipie#175] declared for identity constraint of element "speed".
```

[0.53.15](https://github.com/zerocracy/farm): CID: [629442c7-3e14-4e89-a625-5bf205ac5193](https://www.0crat.com/footprint/CT2E6TK9B/629442c7-3e14-4e89-a625-5bf205ac5193), Type: "Order was finished"

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
