### ISSUE TITLE
NPM authentication documentation is missed

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#176]
I tried to create NPM account using `npm` tool for Central registry with this command:
```bash
npm adduser --loglevel silly --registry=https://central.artipie.com/npm --always-auth
```
I've entered valid username and password but got 401 error:
```
npm verb login before first PUT {
npm verb login   _id: 'org.couchdb.user:artipie',
npm verb login   name: 'artipie',
npm verb login   password: 'XXXXX',
npm verb login   type: 'user',
npm verb login   roles: [],
npm verb login   date: '2020-05-27T13:34:21.893Z'
npm verb login }
npm http fetch PUT 401 https://central.artipie.com/npm/-/user/org.couchdb.user:artipie 796ms
npm verb adduser before first PUT {
npm verb adduser   _id: 'org.couchdb.user:artipie',
npm verb adduser   name: 'artipie',
npm verb adduser   password: 'XXXXX',
npm verb adduser   email: 'g4s8.public@gmail.com',
npm verb adduser   type: 'user',
npm verb adduser   roles: [],
npm verb adduser   date: '2020-05-27T13:34:22.690Z'
npm verb adduser }
npm http fetch PUT 401 https://central.artipie.com/npm/-/user/org.couchdb.user:artipie 271ms
npm verb stack Error: 401 Unauthorized - PUT https://central.artipie.com/npm/-/user/org.couchdb.user:artipie
npm verb stack     at /usr/lib64/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15
npm verb stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm verb statusCode 401
```
It seems I configured auth wrong.

**Comment by 0crat** [comment]
The job [#176](https://github.com/artipie/artipie/issues/176) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/54c585bf-2217-4430-89e1-b03b5c0887e5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by brastak** [comment]
@g4s8 Please, do the following 
1. Calculate `base64` of the `user:password` string:
    `$ echo -n 'user:password' | base64`
2. Edit yout `$HOME/.npmrc` file:
    ```
   always-auth=true
   _auth=<base64 string>
   ```

Based on [Nexus manaul](https://help.sonatype.com/repomanager3/formats/npm-registry#npmRegistry-AuthenticationUsingBasicAuth)

The real question - do we need to support PUT user operation? I don't think that it is required. If so, I just put this instruction to documentation

**Comment by g4s8** [comment]
@brastak how can I add additional credentials if I have it for registry.npmjs.org already? It seems my `.rpmrc` has different format:
```
//registry.npmjs.org/:_authToken=xxxxx
```

> The real question - do we need to support PUT user operation?

What does this `PUT` (`https://central.artipie.com/npm/-/user/org.couchdb.user:artipie`) request actually do? Do we need to process this data later? Does `npm` tool expects some content to be returned?

**Comment by brastak** [comment]
@g4s8 

> how can I add additional credentials if I have it for registry.npmjs.org already? It seems my `.rpmrc` has different format:

You should add `//central.artipie.com/npm/:_authToken=xxxx` in this case

> What does this `PUT` (`https://central.artipie.com/npm/-/user/org.couchdb.user:artipie`) request actually do? Do we need to process this data later? Does `npm` tool expects some content to be returned?

Need to be reverse-engineered ) it `creates or verifies` user. In our case - just verifies. If all is ok, it put `_authToken` to `.npmrc`. But I have no idea what can be `all is ok` and how npm processed the response from registry

**Comment by g4s8** [comment]
@brastak can we just allow put for `/-/user/org.couchdb.user` using Artipie authorization mechanisms?

**Comment by brastak** [comment]
@g4s8 No, it's little bit harder. User and password are sent with message payload instead of auth  header

**Comment by g4s8** [comment]
@brastak got it. Then I'd put [your comment](https://github.com/artipie/artipie/issues/176#issuecomment-635183955) to the README file, and start implementing payload parsing with lower priority.

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @brastak[/z](https://www.0crat.com/u/brastak) resigned from [#176](https://github.com/artipie/artipie/issues/176), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#176` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#176](https://github.com/artipie/artipie/issues/176) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f6c93e1c-06d5-45cc-a3fe-39843bdd841a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat  refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/176#issuecomment-640082610))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#176](https://github.com/artipie/artipie/issues/176), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/176#issuecomment-640082610))

@victornoel Job refused in 2 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#176](https://github.com/artipie/artipie/issues/176) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f1827ed9-26bd-48a3-a9d0-208f2fd10302); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by marceloamadeu** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/176#issuecomment-640718179))

@marceloamadeu The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#176](https://github.com/artipie/artipie/issues/176), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/176#issuecomment-640718179))

@marceloamadeu Job refused in 0 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by paulodamaso** [comment]
@g4s8 Should I go on adding the solution to `readme.md` or you'll re-assign @brastak since he provided the actual solution?

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for @g4s8 definition

**Comment by paulodamaso** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@paulodamaso yes, you can add it in the readme

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/artipie/artipie/pull/310

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/artipie/artipie/pull/310 ([here](https://github.com/artipie/artipie/issues/176#issuecomment-656817296))

@paulodamaso Job [#176](https://github.com/artipie/artipie/issues/176) is already on hold

**Comment by paulodamaso** [comment]
@g4s8 merged, please close

**Comment by g4s8** [comment]
@paulodamaso thanks
