### ISSUE TITLE
YamlSettings.java:128-129: Extract this method to a...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#179]
The puzzle `146-3820475f` from #146 has to be resolved: 

https://github.com/artipie/artipie/blob/41aab38cffcda2d1317756c701b3a47572c34e9b/src/main/java/com/artipie/YamlSettings.java#L128-L129

The puzzle was created by @olenagerasimova on 22-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `146-3820475f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#179` is not assigned, can't get performer
