### ISSUE TITLE
AuthFromYaml.java:36-41: Consider adding opportunity to...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#180]
The puzzle `146-b7fdde7c` from #146 has to be resolved: 

https://github.com/artipie/artipie/blob/41aab38cffcda2d1317756c701b3a47572c34e9b/src/main/java/com/artipie/auth/AuthFromYaml.java#L36-L41

The puzzle was created by @olenagerasimova on 22-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
I think we can use `aliases` optional list, not just single alternative login string:
```yaml
joe: 
  aliases:
    - joe@mail.com 
    - joe123@artipie.com
  pass: "plain:123"
```
