### ISSUE TITLE
Get rid of path config parameter

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#185]
Some repositories have `path` config parameter, some don't have it. I think we can remove it safely from config, since we always know what is the path of current request. Even if we switch to another routing schema #178 we still be able to get the path from request on top level. So we can remove it from config and specify directly. @artipie/contributors do you agree?

**Comment by olegmoz** [comment]
@g4s8 this makes perfect sense for now when we are mapping all repos by path prefix. This won't work for more complex scenario for Docker, when repo name is in the middle of path (something like `/v2/docker-local/my-image/manifest/latest`). But I am not sure we really need to support this case now or ever.

**Comment by 0crat** [comment]
The job [#185](https://github.com/artipie/artipie/issues/185) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f0d14b68-fbb6-426f-a3c4-24ba286cb30c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @brastak[/z](https://www.0crat.com/u/brastak) resigned from [#185](https://github.com/artipie/artipie/issues/185), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#185](https://github.com/artipie/artipie/issues/185) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/12128c53-5059-4b66-8e44-ca683a11a076); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by marceloamadeu** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/185#issuecomment-645739227))

@marceloamadeu The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#185](https://github.com/artipie/artipie/issues/185), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#185](https://github.com/artipie/artipie/issues/185) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1a0ad16d-0fba-44b1-876e-37a25a8758f4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@g4s8 should we aim to have the path parameter of all adapters' slices removed too while we are at it?

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@victornoel not all, some `Slice` implementations needs to know what's the full path of URI (e.g. Docker, NPM) but some doesn't need it (Maven, RPM). So we need to get this path prefix from URI directly instead of using configuration files.

**Comment by victornoel** [comment]
@g4s8 so they should be removed from the constructors though, no? (and of course the implementation should then be changed to accommodate from what you just said). Do I need to include that in the scope of this issue (i.e., create new todos, tickets, etc) or is that already taken care of in each of the repositories?

**Comment by victornoel** [comment]
@0crat wait

**Comment by g4s8** [comment]
> @g4s8 so they should be removed from the constructors though, no? (and of course the implementation should then be changed to accommodate from what you just said). Do I need to include that in the scope of this issue (i.e., create new todos, tickets, etc) or is that already taken care of in each of the repositories?

@victornoel I don't think so, some `Slice` implementations may need this `path` parameter. Current issues, is that we're specifying it in yaml configuration when we can just know it programmatically.

**Comment by victornoel** [comment]
@g4s8 so if I understand correctly, for example the url `http://localhost:8080/foo` will use the yaml repo config yaml named `foo.yaml` and thus the slice that is instantiated should take "/" as the path argument? or should it take `foo`?

**Comment by victornoel** [comment]
@g4s8 ping :)

**Comment by g4s8** [comment]
> @g4s8 so if I understand correctly, for example the url `http://localhost:8080/foo` will use the yaml repo config yaml named `foo.yaml` and thus the slice that is instantiated should take `/` as the path argument? or should it take `foo`?

It should be `/foo` in your example.

**Comment by victornoel** [comment]
@0crat wait for #275 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #275 to be merged ([here](https://github.com/artipie/artipie/issues/185#issuecomment-655002245))

@victornoel Job [#185](https://github.com/artipie/artipie/issues/185) is already on hold

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/185#issuecomment-673372468))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#185](https://github.com/artipie/artipie/issues/185), please stop working. Reason for job resignation: Order was cancelled

**Comment by g4s8** [comment]
Fixed in #275
