### ISSUE TITLE
YamlSettingsTest.java:48-49: Add a test for layout...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#191]
The puzzle `187-870a4b1d` from #187 has to be resolved: 

https://github.com/artipie/artipie/blob/06a5670f84dde0e7de5e479869e70df106d47310/src/test/java/com/artipie/YamlSettingsTest.java#L48-L49

The puzzle was created by @g4s8 on 02-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `187-870a4b1d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#191` is not assigned, can't get performer
