### ISSUE TITLE
Update NuGet to 0.2 with authentication support

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#192]
NuGet 0.2 supports authentication and could be integrated into Artipie

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#192` is not assigned, can't get performer
