### ISSUE TITLE
Repository configuration cache

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#195]
Artipie performs a lot of read operations for repository configs, it would be better to cache these configs in memory. The config can be updated at any time, so we need to drop cached value after some time, e.g. after few minutes. Consider using soft references to avoid OOM errors when working with many repos.

**Comment by 0crat** [comment]
The job [#195](https://github.com/artipie/artipie/issues/195) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/51e4830c-4254-4f2d-802f-7483a64661b7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @brastak[/z](https://www.0crat.com/u/brastak) resigned from [#195](https://github.com/artipie/artipie/issues/195), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#195](https://github.com/artipie/artipie/issues/195) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/c264f400-6ce4-4cc1-b288-35acd6d9ccf7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@g4s8 can you explain a bit more in details the current architecture and where does this caching should happen? To be honest, the current code is really hard to understand, between the RepoLayout, StorageAliases, RepoConfig and so on, I'm a bit lost :)

**Comment by g4s8** [comment]
@victornoel can you please report a bug and explain what exactly is not clear? I'll fix the documentation.
Right now we are reading Yaml file on each request using `RepoConfig`. The actual read operation is performed in `RepoLayout` implementation lambdas (see `RepoConfig.fromPublisher` usages).

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/195#issuecomment-646965114))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#195](https://github.com/artipie/artipie/issues/195), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#195](https://github.com/artipie/artipie/issues/195) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/59a3c9c6-2e0b-4d9a-b5e4-cbe3261d039d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/195#issuecomment-662293499))

@g4s8 The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#195](https://github.com/artipie/artipie/issues/195), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by marceloamadeu** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/195#issuecomment-662515223))

@marceloamadeu The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#195](https://github.com/artipie/artipie/issues/195), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/195#issuecomment-662515223))

@marceloamadeu Job refused in 0 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)
