### ISSUE TITLE
Support for hierarchies of any level

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#196]
How about dynamic hierarchies configuration?
If a hierarch of repository configs is flat:
```
├── gem.yaml
└── maven.yaml
```
let the layout be flat as well.

But what if config storage structure is the following:
```
├── depatmet-1
│   └── dev
│       ├── gem.yaml
│       └── maven.yaml
└── depatmet-2
    └── dev
        ├── gem.yaml
        └── maven.yaml
```

The pathes for the repositories should be `/depatmet-1/dev/gem/`,  `/depatmet-1/dev/maven/`, etc...

I think that paths should be dependent on storage structure and dynamically defined by a user. This would also allow hierarchies of any level.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@Sammers21 it sounds interesting but this solution has some missed parts in this proposal:
 1. How Artipie resolves repository for request in this case? Assume it receives `PUT /one/two/three/four` request, it may be treated as `PUT /two/three/four` into `one` repository, `PUT /three/four` into `one/two` repository or `PUT /four` into `one/two/three` repository.
 2. How to manage permissions? One of the points of of two level hierarchy #178 is to have organization administrator who can publish and update repository configs, e.g. user `john` can create or modify new repositories under `john/*` namespace. How would you suggest organizing authorization for 3 and more levels hierarchy? 

@artipie/contributors, @jeffzhu503 what do you think about this feature?

**Comment by jeffzhu503** [comment]
Let me first propose one solution which was adopted from Chartmuseum, another open source project.  That project experienced the same thing.  It uses a configurable variable named depth. The depth can be set to 0-3. However, each domain can only have one fixed level.  For example, Aritpie.com is set to depth=2. Then you always expect users to provide the url as /org/repo.  If you set to 3, you always expect users to /org/user/repo.  You can use your UI project to have the control of this depth which enforces client to always pass the same depth of level.  
For enterprise installation, when your enterprise installs Artipie internally, they will have to decide that value of "depth". 
Btw, you shall have some configuration model in your Java framework that you can always extend the set of configurations.

**Comment by Sammers21** [comment]
@g4s8, I would fully agree with the idea, suggested by @jeffzhu503: it is very simple and cheap to implement. But, I would also consider the following:

> How Artipie resolves repository for request in this case? Assume it receives PUT /one/two/three/four request, it may be treated as PUT /two/three/four into one repository, PUT /three/four into one/two repository or PUT /four into one/two/three repository.

To restrict naming: files and directories could not have the same name: so `one.yaml` and `one/` in the root dir would not work together. With the restriction, having a tree structure of storage you can resolve a request ambiguously.

> How to manage permissions? One of the points of of two level hierarchy #178 is to have organization administrator who can publish and update repository configs, e.g. user john can create or modify new repositories under john/* namespace. How would you suggest organizing authorization for 3 and more levels hierarchy?

By referring to an exact leaf of the tree. Consider the following example with a flat structure:
```
├── gem.yaml
└── maven.yaml
```

The following permission configuration would give `john` full permissions for the whole instance: 
```
permissions:
 - john: "/"
```

While with this `john` will be able to modify the `gem.yaml` file:
```
permissions:
  john: 
       modify:
          -  "/gem.yaml"
```

The same could work with `directories`. You just refer to a specific leaf of the storage tree and being granted with specific permission only in a specific area of the tree.

The main benefit is that it is very simple to use because of the dynamic nature.

**Comment by jeffzhu503** [comment]
I am not sure why you need to put the restriction here.  Once you have depth fixed, your router shall be able to tell which part of url is the repo name.  For example, 
For example, one of routes is "POST", "api/:repo/artifact".  Now the user curl api/one/two/artifact will upload the new artifact to the repo.  If the user curl api/one/two/three/four, your server may respond with "invalid path or not successful".
