### ISSUE TITLE
Artipie logging

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#197]
Enable logging messages:
 - [x] request logging with headers c377387
 - [x] errors in adapter logging c377387
 - [x] storage access logging (read, write operations) 9dde10a6298d1f824f3b257e1da739f0b435dc1f
 - [x] authentication & authorization logging (e.g. `access <granted|denied> for <user> in <repo> to perform <action>`)

@artipie/contributors what else do we need to be logged?

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.2`

**Comment by g4s8** [comment]
Done fully

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#197` is not assigned, can't get performer
