### ISSUE TITLE
Benchmarks are not running on releases

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#198]
There are no benchmark reports in `gh-pages` branch: https://github.com/artipie/artipie/commits/gh-pages
It seems report tool is not working correctly.

**Comment by 0crat** [comment]
The job [#198](https://github.com/artipie/artipie/issues/198) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ae853f80-d87a-4a87-9b36-287731012a7e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @brastak[/z](https://www.0crat.com/u/brastak) resigned from [#198](https://github.com/artipie/artipie/issues/198), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#198](https://github.com/artipie/artipie/issues/198) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/c95b6f03-ed92-4c35-b216-e9242b51d549); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@g4s8 @olenagerasimova please make a release to validate it works now

**Comment by victornoel** [comment]
@brastak the changes you made in #202 didn't seem to fix the problem. Do you know why? I will try to solve it now that the task is assigned to me.

**Comment by victornoel** [comment]
@0crat wait for answer

**Comment by brastak** [comment]
@victornoel Benchmarks script is run but fails when pushes jmeter report to `gh-pages` branch. It looks like that the main reason is the base settings for this branch - PR is required to allow push for branch. @g4s8 I think we need to remove this rule from `gh-pages` branch and restrict access with users whitelist. I could not find the reasonable alternative for this.

Also I have created PR to increase run stability: https://github.com/artipie/benchmarks/pull/16

One more thing, last few builds produced errors when running tests (at least, `0.6.7` and looks like `0.6.8`). I think, this is some configuration issue (`0.6.5` build run successfully), but this investigation still in progress

**Comment by victornoel** [comment]
@g4s8 I have verified, the benchmarks now seem to be present since latest release: https://github.com/artipie/artipie/tree/gh-pages/benchmarks

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/artipie/issues/198#issuecomment-648617315))

@victornoel This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#198](https://github.com/artipie/artipie/issues/198) is [in scope](http://www.zerocracy.com/policy.html#14) for 20days
  * The role is `DEV`
  * The job is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel) for [10days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @victornoel[/z](https://www.0crat.com/u/victornoel) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
    * @brastak[/z](https://www.0crat.com/u/brastak): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fartipie%23198%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@g4s8 0crat didn't notice the close

**Comment by victornoel** [comment]
@g4s8 please can you do something :)

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#198](https://github.com/artipie/artipie/issues/198), since the job is not in scope anymore
