### ISSUE TITLE
Submit the talk proposal to Europe Open Source Summit in Dublin, Ireland Oct 26-28, 2020

### ISSUE THREAD

**Issue by jeffzhu503** [artipie/artipie#200]
We shall use this summit to present our new open source project - Artipie. 
https://events.linuxfoundation.org/open-source-summit-europe/. (At least this one)
https://events.linuxfoundation.org/open-source-summit-japan/ (Optional)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue
