### ISSUE TITLE
[ERROR] JSR-303 validator thrown during initialization: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException

### ISSUE THREAD

**Issue by jeffzhu503** [artipie/artipie#204]
1. Git clone artipie repo to Mac local directory. 
2. Add the following section from central into the pom.xml after <distributionManagement> 
3. Run mvn package 
Error: [ERROR] JSR-303 validator thrown during initialization: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)

From central.artipie.com  
<project>
  [...]
  <pluginRepositories>
    <pluginRepository>
      <id>artipie</id>
      <name>artipie plugins</name>
      <url>http://central.artipie.com/maven</url>
    </pluginRepository>
  </pluginRepositories>
  <repositories>
    <repository>
      <id>artipie</id>
      <name>artipie builds</name>
      <url>http://central.artipie.com/maven</url>
    </repository>
  </repositories>
</project>

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by g4s8** [comment]
@jeffzhu503 it's not an Artipie issue, it's a error log from one of the build plugins, see: https://github.com/jcabi/jcabi-maven-plugin/issues/59

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#204` is not assigned, can't get performer
