### ISSUE TITLE
Speed up docker build

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#205]
Create base image with build dependencies

**Comment by 0crat** [comment]
The job [#205](https://github.com/artipie/artipie/issues/205) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1228d0e2-3330-4d90-a248-e1d73f57eca4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.6.4`

**Comment by g4s8** [comment]
Done

**Comment by 0crat** [comment]
Job was finished in 5 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by g4s8** [comment]
@rultor release, tag=`0.6.5`
