### ISSUE TITLE
Update Docker repo

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#207]
Update docker to `0.2.4` with 500 error fix: https://github.com/artipie/docker-adapter/issues/212

**Comment by g4s8** [comment]
@rultor release, tag=`0.6.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.6.7`

**Comment by g4s8** [comment]
@rultor release, tag=`0.6.8`

**Comment by g4s8** [comment]
@olegmoz done: now it's working for upload and download, I've managed to push and pull `alpine` image to central.artipie.com

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#207` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@g4s8 great to hear that! Finally :)
