### ISSUE TITLE
Missed example configuration

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#211]
Add example config files to start Artipie server locally

**Comment by 0crat** [comment]
The job [#211](https://github.com/artipie/artipie/issues/211) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/46150c32-ca61-4750-a16d-ada88f34eeaa); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@artipie/contributors see the readme update, now you can start Artipie server with example configuration files in one line

**Comment by 0crat** [comment]
Job was finished in 5 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
