### ISSUE TITLE
the name of the repo is not visible in repo.hbs

### ISSUE THREAD

**Issue by yegor256** [artipie/artipie#217]
Check the content of `repo.hbs`. A the bottom it gives a link, but it's not complete. Let's make the repo name visible there, from Java.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#217](https://github.com/artipie/artipie/issues/217) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/0dff745f-16f3-4038-96bd-164f9d43dd3c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@yegor256 fixed in https://github.com/artipie/artipie/commit/82efc6dbf4dc26a6fe430f31bb809e3923ed623f
