### ISSUE TITLE
Reset password form

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#218]
Let's add a reset password form on user page, to allow users generate passwords for HTTP basic authentication.

**Comment by 0crat** [comment]
The job [#218](https://github.com/artipie/artipie/issues/218) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/7539702e-f541-4de0-ba49-e2b5a31414ef); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
Done
