### ISSUE TITLE
Data model for artipie

### ISSUE THREAD

**Issue by jeffzhu503** [artipie/artipie#22]
Please create a data model (or link to an existing one) for the artipie project.  Something like this
Project: ID, name, namespace
ProjectVersion: ID, Version, repsitoryID, etc
Artifact: ID, namespace, etc,
Repository: .....
.....

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@jeffzhu503[/z](https://www.0crat.com/u/jeffzhu503) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@jeffzhu503 should be fixed in #29

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#22` is not assigned, can't get performer
