### ISSUE TITLE
HTTP proxy configuration

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#222]
Add http proxy configuration for HTTP client

**Comment by 0crat** [comment]
The job [#222](https://github.com/artipie/artipie/issues/222) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3c01ec80-2217-472a-8b55-2f945778464d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.7.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.7.3`

**Comment by g4s8** [comment]
Done in #223
