### ISSUE TITLE
Release workflow seems to be run on each commit

### ISSUE THREAD

**Issue by victornoel** [artipie/artipie#229]
When looking at https://github.com/artipie/artipie/actions?query=workflow%3A%22Docker+Release+and+Run+Benchmarks%22, it shows that the workflow runs (and fail, luckily) for each commit instead of each release. I don't think that it is expected, is it?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by g4s8** [comment]
@victornoel thanks, should be fixed: https://github.com/artipie/artipie/commit/929f9ea612f279d4bbf2acfc347f1ec098eeb7c6

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#229` is not assigned, can't get performer
