### ISSUE TITLE
Collect Artipie metrics

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#231]
Add interface to collect Artipie metrics for some common events. This interface is going to be connected to third-party services later. For the first stage, we may just print metrics to log output. Let's start with these metrics:
 - artifact uploaded
 - artifact downloaded
 - artifact upload error
 - artifact download error
 - not authenticated
 - not authorized

Feel free to suggest more metrics or discuss existing.

**Comment by 0crat** [comment]
The job [#231](https://github.com/artipie/artipie/issues/231) assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1996f5a6-f807-467b-a159-2b5082fbfa5e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @olegmoz[/z](https://www.0crat.com/u/olegmoz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by olegmoz** [comment]
@g4s8 as the metrics are collected in Artipie we can operate only on HTTP request/response level of abstractions, so collecting counters of artifacts uploads and downloads is not really possible. What I propose instead is to collect number of success and error requests by method. Error responses have status code `4xx` or `5xx`, all others considered to be success.

Unauthenticated requests could be identified when response has 403 status and there was no `Authorized` header in request.

Not authorized requests could be identified when response has 403 status and there is some `Authorized` header in request.

Sounds good?

**Comment by g4s8** [comment]
@olegmoz yes, sounds good, let's start with these metrics

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#267](https://github.com/artipie/artipie/issues/267) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#267](https://github.com/artipie/artipie/issues/267), [#272](https://github.com/artipie/artipie/issues/272), [#273](https://github.com/artipie/artipie/issues/273) are still not solved.

**Comment by 0pdd** [comment]
@g4s8 5 puzzles [#267](https://github.com/artipie/artipie/issues/267), [#272](https://github.com/artipie/artipie/issues/272), [#273](https://github.com/artipie/artipie/issues/273), [#290](https://github.com/artipie/artipie/issues/290), [#291](https://github.com/artipie/artipie/issues/291) are still not solved.

**Comment by 0pdd** [comment]
@g4s8 6 puzzles [#267](https://github.com/artipie/artipie/issues/267), [#272](https://github.com/artipie/artipie/issues/272), [#273](https://github.com/artipie/artipie/issues/273), [#290](https://github.com/artipie/artipie/issues/290), [#291](https://github.com/artipie/artipie/issues/291), [#292](https://github.com/artipie/artipie/issues/292) are still not solved.

**Comment by 0crat** [comment]
Job [#231](https://github.com/artipie/artipie/issues/231) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title

**Comment by 0crat** [comment]
Job [#231](https://github.com/artipie/artipie/issues/231) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olegmoz[/z](https://www.0crat.com/u/olegmoz), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@g4s8 4 puzzles [#272](https://github.com/artipie/artipie/issues/272), [#273](https://github.com/artipie/artipie/issues/273), [#291](https://github.com/artipie/artipie/issues/291), [#292](https://github.com/artipie/artipie/issues/292) are still not solved; solved: [#267](https://github.com/artipie/artipie/issues/267), [#290](https://github.com/artipie/artipie/issues/290).

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#273](https://github.com/artipie/artipie/issues/273), [#291](https://github.com/artipie/artipie/issues/291), [#292](https://github.com/artipie/artipie/issues/292) are still not solved; solved: [#267](https://github.com/artipie/artipie/issues/267), [#272](https://github.com/artipie/artipie/issues/272), [#290](https://github.com/artipie/artipie/issues/290).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#273](https://github.com/artipie/artipie/issues/273), [#291](https://github.com/artipie/artipie/issues/291) are still not solved; solved: [#267](https://github.com/artipie/artipie/issues/267), [#272](https://github.com/artipie/artipie/issues/272), [#290](https://github.com/artipie/artipie/issues/290), [#292](https://github.com/artipie/artipie/issues/292).

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#273](https://github.com/artipie/artipie/issues/273), [#291](https://github.com/artipie/artipie/issues/291), [#734](https://github.com/artipie/artipie/issues/734) are still not solved; solved: [#267](https://github.com/artipie/artipie/issues/267), [#272](https://github.com/artipie/artipie/issues/272), [#290](https://github.com/artipie/artipie/issues/290), [#292](https://github.com/artipie/artipie/issues/292).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#273](https://github.com/artipie/artipie/issues/273), [#291](https://github.com/artipie/artipie/issues/291) are still not solved; solved: [#267](https://github.com/artipie/artipie/issues/267), [#272](https://github.com/artipie/artipie/issues/272), [#290](https://github.com/artipie/artipie/issues/290), [#292](https://github.com/artipie/artipie/issues/292), [#734](https://github.com/artipie/artipie/issues/734).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#291](https://github.com/artipie/artipie/issues/291) is still not solved; solved: [#267](https://github.com/artipie/artipie/issues/267), [#272](https://github.com/artipie/artipie/issues/272), [#273](https://github.com/artipie/artipie/issues/273), [#290](https://github.com/artipie/artipie/issues/290), [#292](https://github.com/artipie/artipie/issues/292), [#734](https://github.com/artipie/artipie/issues/734).
