### ISSUE TITLE
How to point mvn to central.artipie.com?

### ISSUE THREAD

**Issue by jeffzhu503** [artipie/artipie#235]
I am running the following command to create Maven project. 
mvn archetype:generate -DgroupId=com.jcg.maven -DartifactId=MavenHelloWorldProject -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
Mvn will download a lot of components from central, https://repo.maven.apache.org.  Can we point mvn to the central.artipie.com?

**Comment by g4s8** [comment]
@jeffzhu503 try adding `mirrors` to you `~/.m2/settings.xml` https://github.com/artipie/artipie#maven-proxy-repo
To mirror all remotes not only Maven central, use `*` instead of `central`:
```xml
<settings>
  <mirrors>
    <mirror>
      <id>artipie-mirror</id>
      <name>Artipie Mirror Repository</name>
      <url>https://central.artipie.com/mirrors/maven-central</url>
      <mirrorOf>*</mirrorOf>
    </mirror>
  </mirrors>
</settings>
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
the answer is provided in the upper comment
