### ISSUE TITLE
Integrate Maven proxy with cache

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#236]
Release Maven proxy with cache and integrate into Artipie.

Depends on https://github.com/artipie/maven-adapter/issues/98

**Comment by 0crat** [comment]
The job [#236](https://github.com/artipie/artipie/issues/236) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ce2b0dbf-f56d-40cf-b8d0-597679b304ce); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.7.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.7.7`

**Comment by g4s8** [comment]
@rultor release, tag=`0.7.8`

**Comment by g4s8** [comment]
Done

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.1`
