### ISSUE TITLE
Authentication methods for artipie

### ISSUE THREAD

**Issue by jeffzhu503** [artipie/artipie#24]
We should provide opportunity to implement and use a custom auth method.

Which will be implemented in Artipie from the box: 
- [x] - Users log into Artipie via user-name and password;
- [x] - GitHub tokens;
- [x] - Users to authenticate using [KeyCloack](https://www.keycloak.org/).
- [x] - Custom auth method (create according abstractions);

- ~authenticate using SAML SSO providers like ADFS, OneLogin and Okta.~ (won't be implemented, since repository authentication mechanisms doesn't support these providers).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@jeffzhu503[/z](https://www.0crat.com/u/jeffzhu503) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
