### ISSUE TITLE
Get rid of mapping() and string() methods in YamlSettings

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#25]
These methods were added because YAML library we use doesn't check for presence of value by key and just return `null`. We can change library, improve this library or think of some other solution maybe.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by Guseyn** [comment]
@olegmoz close the ticket, please

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#25` is not assigned, can't get performer
