### ISSUE TITLE
HTTP layer refactoring

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#258]
Artipie has a lot of prototyping code which becomes production. Let's refactor all stable components in http layer.

**Comment by 0crat** [comment]
The job [#258](https://github.com/artipie/artipie/issues/258) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/8e8dd995-fe85-4600-a019-83c4166d2adf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
Done
