### ISSUE TITLE
Maven proxy unable to reply HTTP over HTTPS connection

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#261]
Maven proxy fails for package https://central.artipie.com/g4s8/maven/org/slf4j/slf4j-simple/1.7.21/slf4j-simple-1.7.21.pom:
```
artipie         | [ERROR] 2020-07-06 12:44:40,698 HttpClient@153dbf2e-24 com.artipie.maven.http.DownloadMavenSlice - Failed to download artifact: java.io.EOFException: HttpConnectionOverHTTP@11236682::DecryptedEndPoint@55bab3f{l=/192.168.16.3:54178,r=repo.maven.apache.org/151.101.24.215:443,OPEN,fill=-,flush=-,to=10196082/0}
artipie         | 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:345)
artipie         | 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1595)
artipie         | 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:237)
artipie         | 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:176)
artipie         | 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:75)
artipie         | 	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
artipie         | 	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:156)
artipie         | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
artipie         | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
artipie         | 	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:543)
artipie         | 	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:398)
artipie         | 	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
artipie         | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
artipie         | 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
artipie         | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
artipie         | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
artipie         | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
artipie         | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
artipie         | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
artipie         | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
artipie         | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
artipie         | 	at java.base/java.lang.Thread.run(Unknown Source)
```

Fixed after restart.

**Comment by 0crat** [comment]
The job [#261](https://github.com/artipie/artipie/issues/261) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/853ee347-211a-49cb-8aeb-8027899e3910); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@g4s8 could you please provide more information abou this one?

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@paulodamaso sure:
 - this error happens time to time
 - it's fixing after instance restart
 - it's stable when happens: if this error happens Artipie will not be able to resolve this dependency until restart

Let me know if you need more details.

**Comment by paulodamaso** [comment]
@g4s8 I need some other information:
- how are you running the artipie code? What is your configuration?

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/261#issuecomment-670529871))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#261](https://github.com/artipie/artipie/issues/261), please stop working. Reason for job resignation: Order was cancelled

**Comment by g4s8** [comment]
@olenagerasimova could you please check or close it if no longer valid?

**Comment by olenagerasimova** [comment]
Does not seem valid to me, `MavenProxySliceITCase` covers this case and passes now
