### ISSUE TITLE
Artipie documentation on create repo page is not correct

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#264]
The documentation says
```
<project>
  [...]
  <distributionManagement>
    <snapshotRepository>
      <id>artipie</id>
      <url>https://central.artipie.com/g4s8/maven</url>
    </snapshotRepository>
  </distributionManagement>
  <repositories>
    <repository>
      <id>artipie</id>
      <url>https://central.artipie.com/g4s8/maven</url>
    </repository>
  </repositories>
</project>
```

It's not correct, it should be the same as on the readme page.

**Comment by 0crat** [comment]
The job [#264](https://github.com/artipie/artipie/issues/264) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/2b63bbc7-b5c9-440c-a187-1d02cf411152); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
not relevant, no such test in docs now
