### ISSUE TITLE
InMemoryMetrics.java:36-39: Support gauges in...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#267]
The puzzle `231-69751ecf` from #231 has to be resolved: 

https://github.com/artipie/artipie/blob/a5fd2ac67c624bb837561250418d608c4526c335/src/main/java/com/artipie/metrics/memory/InMemoryMetrics.java#L36-L39

The puzzle was created by @olegmoz on 06-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `231-69751ecf` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
