### ISSUE TITLE
Pie.java:113-115: Move all Async* implementation to...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#27]
The puzzle `12-c03f07e2` from #12 has to be resolved: 

https://github.com/artipie/artipie/blob/db18891ef5922576892a07e3d45af8e82219fd9c/src/main/java/com/artipie/Pie.java#L113-L115

The puzzle was created by @g4s8 on 13-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `12-c03f07e2` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#27` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job [#27](https://github.com/artipie/artipie/issues/27) is closed, can't start order
