### ISSUE TITLE
ResponseMetricsSlice.java:45-48: Report exceptions as...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#273]
The puzzle `231-bfc96007` from #231 has to be resolved: 

https://github.com/artipie/artipie/blob/36a1c5a395adebe1d657e1f55718d47e66666eb4/src/main/java/com/artipie/ResponseMetricsSlice.java#L45-L48

The puzzle was created by @olegmoz on 07-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue
