### ISSUE TITLE
Special routing for Docker registry

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#274]
Artipie may have different path layouts (flat paths like `/repo-name` and org like `/org-name/repo-name`). But docker registry endpoints starts with `/v2` prefixes. Maybe we can handle this case on Artipie level: some `Slice` implementation intercepts requests like virtual proxy starting with `/v2` and redirect it to underlying `Slice` implementations. @artipie/contributors WDYT?

**Comment by olegmoz** [comment]
@g4s8 we may have special case for empty repository name, it could be always mapped to Docker

**Comment by 0crat** [comment]
The job [#274](https://github.com/artipie/artipie/issues/274) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/93888055-362c-4fa7-ad11-b1413023b1da); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
Fixed in #293
