### ISSUE TITLE
Artipie user experience is completely broken: user interface

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#276]
When you start artipie locally, the message is displayed:
```
Artipie was started on port 8080
```
Then a user tries to visit localhost:8080, and, what user gets here is just NOTHING:
```
curl -i http://localhost:8080/
HTTP/1.1 204 No Content
```
There is no way for a user to get to a dashboard

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by g4s8** [comment]
@Sammers21 keep in mind that dashboard is available only for organization based repository layout, we can't show dashboard for flat structure.

We may check auth headers and redirect user to profile page if auth is valid, or ask for credentials otherwise, would it be ok?

**Comment by g4s8** [comment]
Closing as out of date
