### ISSUE TITLE
Issues in the repository is managed in a bad way

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#278]
* Some of the issues in are not up to date
* The external contributors are not welcome because they don't know where they can help
* Tagging is inconsistent
* Discussions in some of the issues completely spammed with bots

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by g4s8** [comment]
@Sammers21 can you provide more details:

> Some of the issues in are not up to date

What issues are not up to date? 

> Tagging is inconsistent

What did you mean by this?
