### ISSUE TITLE
High Availability requirements

### ISSUE THREAD

**Issue by jeffzhu503** [artipie/artipie#28]
What is our strategy for the high availability of Artipie?  
For example, in Apache Archiva project, it supports two different installations
Option 1: master-slave-strategy (not really a cluster).  This option may not be good enough for us, as there will be downtime when upgrade happens.
Option 2: two Servers + httpd-balancer + shared file system. How can we keep the file system synced if necessary? 
In our case, we might also need to support multiple regions installation.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@jeffzhu503[/z](https://www.0crat.com/u/jeffzhu503) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@jeffzhu503 you are right, we are going to support multi instance cluster installation behind the load balancer by default. Also, it would be possible to start single ARtipie HTTP server. I'll add it to the readme.

**Comment by jeffzhu503** [comment]
Will all instances share the same file storage?  What about the server instances in different regions?

**Comment by g4s8** [comment]
@jeffzhu503 it's recommended to use cloud storage provider for multi-instance environment, e.g. S3 storage.

**Comment by jeffzhu503** [comment]
That is correct.  We need to clarify with our customer in HQ if on-prem installation in multiple regions shall be supported or not.  Also we need to make sure we also support cloud storage such as Ali Cloud and Huawei Cloud mainly used in China.

**Comment by g4s8** [comment]
@jeffzhu503 thanks! I've submitted new storage provider support ticket here: https://github.com/artipie/asto/issues/67

**Comment by Guseyn** [comment]
@jeffzhu503 do we need Google Cloud as well, maybe?

**Comment by jeffzhu503** [comment]
You can always start with a couple of Cloud Providers, as long as your architecture is expandable.

________________________________

**Comment by Guseyn** [comment]
@jeffzhu503 okay thanks
