### ISSUE TITLE
Dashboard may not update repo config elements

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#282]
Some elements may not be updated via dashboard, such as settings or permissions

**Comment by 0crat** [comment]
The job [#282](https://github.com/artipie/artipie/issues/282) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/baf7425d-6118-4062-ade8-e0ba57e14e56); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.4`

**Comment by g4s8** [comment]
Fixed

**Comment by 0crat** [comment]
Job was finished in 28 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
