### ISSUE TITLE
Generate default configuration files

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#284]
Generate default configuration files if doesn't exist on start.

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.14`

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#341](https://github.com/artipie/artipie/issues/341) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.15`

**Comment by g4s8** [comment]
Done

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#284` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#341](https://github.com/artipie/artipie/issues/341) is solved here.
