### ISSUE TITLE
MetricsLogPublisher.java:37-40: Support gauge publishing...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#290]
The puzzle `231-f0ff443a` from #231 has to be resolved: 

https://github.com/artipie/artipie/blob/f8232b260fbb25c3e8be5379ad01c78c18853eec/src/main/java/com/artipie/metrics/memory/MetricsLogPublisher.java#L37-L40

The puzzle was created by @olegmoz on 07-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `231-f0ff443a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
