### ISSUE TITLE
ResponseMetricsSlice.java:94-96: Remove ad-hoc error...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#292]
The puzzle `231-2cd4db3f` from #231 has to be resolved: 

https://github.com/artipie/artipie/blob/3635471e98a4cd15df06e14b2eddceb83f43ea57/src/main/java/com/artipie/ResponseMetricsSlice.java#L94-L96

The puzzle was created by Oleg Mozzhechkov on 08-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#292` is not assigned, can't get performer
