### ISSUE TITLE
Auth required by default and broken

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#295]
Run this:
```bash
java -jar artipie.jar --config-file=./example/artipie.yaml --port=8080
```

`repo.yaml` file:
```yaml
repo:
  type: file
  storage:
    type: fs
    path: /var/artipie/storage
```

When I try to use the storage, I can't do it:

```txt
[INFO] 2020-07-09 10:54:18,469 main com.artipie.VertxMain - Artipie was started on port 8080
[INFO] 2020-07-09 10:54:22,032 vert.x-eventloop-thread-1 com.artipie.http.rt.SliceRoute - >> PUT /repo/white-paper.pdf HTTP_1_1

Host: localhost:8080
User-Agent: curl/7.64.1
Accept: */*
Content-Length: 186491
Content-Type: application/x-www-form-urlencoded
Expect: 100-continue
[INFO] 2020-07-09 10:54:22,063 vert.x-eventloop-thread-1 com.artipie.http.rt.SliceRoute - << UNAUTHORIZED
WWW-Authenticate: Basic
```

The auth should be disabled if it is disabled in the repo file.

When I try to use test as login and pass:123 as a password, I still get 401:
```bash
 curl -u test:plain:123 -i -X PUT --data-binary "@white-paper.pdf" http://localhost:8080/repo/white-paper.pdf
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic
transfer-encoding: chunked
```

**Comment by 0crat** [comment]
The job [#295](https://github.com/artipie/artipie/issues/295) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/6757b6fa-cc4a-4c93-8407-0023371e11f0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@Sammers21 Seems that `ArtipieApi` does not handles `PUT` requests yet, please take a look at the class.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by olenagerasimova** [comment]
This issue is not valid now
