### ISSUE TITLE
Invalid repo name for group repository

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#297]
```
java.util.concurrent.CompletionException: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /var/artipie/repo/---
"artipie/maven-private"
....yaml
java.util.concurrent.CompletionException: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /var/artipie/repo/---
"artipie/maven-private"
```

**Comment by g4s8** [comment]
Fixed in https://github.com/artipie/artipie/commit/65e4ad51ae074fd714072751f34087a95301adc1

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#297` is not assigned, can't get performer

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/artipie/issues/297#issuecomment-656180010))

@g4s8 This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#297](https://github.com/artipie/artipie/issues/297) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fartipie%23297%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
