### ISSUE TITLE
Docker registry doesn't work

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#298]
It seems `/v2/` prefixes are broken for docker.

**Comment by 0crat** [comment]
The job [#298](https://github.com/artipie/artipie/issues/298) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f99e3c55-c87d-47d9-b00c-083bfc1b50bf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by geekdosage** [comment]
Try to create a docker registry according to this [**tutorial**](https://geekdosage.com/how-to-create-a-private-docker-registry-on-centos/)

**Comment by g4s8** [comment]
Fixed in https://github.com/artipie/artipie/commit/dd0433bcaf4c990c9c774a845f234d6dd1b89a31
