### ISSUE TITLE
Layout should be optional by default

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#301]
The layout section should be optional and the value should be `flat` by default

```yaml
layout: org
```

**Comment by g4s8** [comment]
@Sammers21 are you sure it's not optional? It should be already optional right now and `flat` by default.

**Comment by Sammers21** [comment]
@g4s8, it is true, then you should update the `example` dir.

**Comment by g4s8** [comment]
> @g4s8, it is true, then you should update the `example` dir.

@Sammers21 example dir is trying to be as much verbose as it can to show all possible configuration options to a user. I'd keep `layout` there.
