### ISSUE TITLE
Lack of flexibility options

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#303]
Why there is no way to chose: to configure anything in one file, in two files, or to create anything just like in the example? Lack of such simple flexibility seriously damage resulted user experience

**Comment by g4s8** [comment]
@Sammers21 it seems to be a duplicate of #284

**Comment by Sammers21** [comment]
@g4s8, no it is not a duplicate

**Comment by g4s8** [comment]
@Sammers21 can you elaborate? It's not clear from the description. It seems to be a duplicate. Please describe the problem clearly and suggest the solution. What files are you talking about? What are you suggesting?

**Comment by Sammers21** [comment]
@g4s8, if I'm reporting a problem I don't think and should not think about a probable solution

**Comment by Sammers21** [comment]
@g4s8, to make it more clear for you: there is no ability to keep two repositories in one file, or to keep everything in one file, or to keep credentials and permissions in one file while keeping everything else in another.
