### ISSUE TITLE
Artipie prints empty metrics to log

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#305]
When i strart artipie with example config, I get this:
```text
[INFO] 2020-07-10 07:03:46,113 main com.artipie.VertxMain - Artipie was started on port 80
[INFO] 2020-07-10 07:03:51,017 pool-1-thread-1 com.artipie.metrics.Metrics - Counters:
[INFO] 2020-07-10 07:03:56,014 pool-1-thread-1 com.artipie.metrics.Metrics - Counters:
[INFO] 2020-07-10 07:04:01,016 pool-1-thread-1 com.artipie.metrics.Metrics - Counters:
[INFO] 2020-07-10 07:04:06,013 pool-1-thread-1 com.artipie.metrics.Metrics - Counters:
[INFO] 2020-07-10 07:04:11,013 pool-1-thread-1 com.artipie.metrics.Metrics - Counters:
[INFO] 2020-07-10 07:04:16,013 pool-1-thread-1 com.artipie.metrics.Metrics - Counters:
[INFO] 2020-07-10 07:04:21,013 pool-1-thread-1 com.artipie.metrics.Metrics - Counters:
```

The `Counters` printing is completely useless. If there no metrics, why do you print them? Why not printing it only once, filled with zeros and then print them when they appear. The second question is why do they print every 5 seconds and why there is no option to disable it? 

The overall user impression would be: a total inconvenience.

**Comment by g4s8** [comment]
@Sammers21 agree, let's not print empty metrics and configure the interval for logging.

**Comment by Sammers21** [comment]
@g4s8, let's also add an option for metrics to be disabled by default

**Comment by g4s8** [comment]
> @g4s8, let's also add an option for metrics to be disabled by default

@Sammers21 it should be a part of #304 - if we don't put metrics section, then we should not enable it.

**Comment by Sammers21** [comment]
@g4s8, I thing logging interval should be specified in the cron format.

**Comment by g4s8** [comment]
> @g4s8, I thing logging interval should be specified in the cron format.

@Sammers21 yes, it makes a sense. But I would start with more simple configuration for the beginning, e.g. number of seconds.

**Comment by olenagerasimova** [comment]
@Sammers21 #319 was merged, please close this issue

**Comment by olenagerasimova** [comment]
@Sammers21 ping

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#305` is not assigned, can't get performer
