### ISSUE TITLE
Support authentication for Docker proxy repository

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#313]
Remote Docker proxy accessed by proxy may require authentication. It should be possible to specify username and password for such repository. Docker adapter `0.2.9` supports this feature.

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#338](https://github.com/artipie/artipie/issues/338) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olegmoz[/z](https://www.0crat.com/u/olegmoz), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0pdd** [comment]
@olegmoz the only puzzle [#338](https://github.com/artipie/artipie/issues/338) is solved here.
