### ISSUE TITLE
VertxMain.java:38-40: Parse command line options instead...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#32]
The puzzle `12-94a9871a` from #12 has to be resolved: 

https://github.com/artipie/artipie/blob/06c63555f00cf66e662f4d38461585744f43cf8f/src/main/java/com/artipie/VertxMain.java#L38-L40

The puzzle was created by @g4s8 on 21-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#32](https://github.com/artipie/artipie/issues/32) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d72d6c65-6911-4638-a950-38ea7646b73c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `12-94a9871a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#32](https://github.com/artipie/artipie/issues/32) is not in the agenda of @sammers21[/z](https://www.0crat.com/u/sammers21), can't retrieve data and time of add
