### ISSUE TITLE
Drop the repo from the dashboard or API

### ISSUE THREAD

**Issue by jeffzhu503** [artipie/artipie#321]
After I create a "test" repo in the central.artipie, I realize that I can't drop/delete the repo from the site.  We need this feature and the api.

**Comment by genryxy** [comment]
@g4s8 this issue could be closed after merging #981

**Comment by 0pdd** [comment]
@jeffzhu503 the puzzle [#1003](https://github.com/artipie/artipie/issues/1003) is still not solved.
