### ISSUE TITLE
JDK 14 with JEP 358: Helpful NullPointerExceptions enabled for docker image

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#322]
Since NullPointer Exceptions are common in artipie, I would like to suggest to switch to JDK 14 and enable JEP 358.

**Comment by 0crat** [comment]
Job was finished in 26 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @sammers21[/z](https://www.0crat.com/u/sammers21), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed
