### ISSUE TITLE
Binary files download in browser shows a preview of a file

### ISSUE THREAD

**Issue by akuleshov7** [artipie/artipie#327]
It should not be printed like a plain text file. It should trigger a download instead of dummy text.
See: https://central.artipie.com/akuleshov7/file/ktlint

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.13`

**Comment by g4s8** [comment]
@akuleshov7 this bug should be fixed in `0.8.13` release, can we close the ticket?
