### ISSUE TITLE
Support for writes to `docker-proxy` repository

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#332]
If there is storage configured for Docker proxy repository, then it should be possible to do write operations to such repository as well making such repository `virtual`.

**Comment by olegmoz** [comment]
@g4s8 please assign this issue to me

**Comment by 0crat** [comment]
Job was finished in 43 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olegmoz[/z](https://www.0crat.com/u/olegmoz), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed
