### ISSUE TITLE
DockerProxy.java:46-49: Unit test coverage for...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#338]
The puzzle `313-c5cc8405` from #313 has to be resolved: 

https://github.com/artipie/artipie/blob/36d95233470090223c491a89f945f48ad1f55b8c/src/main/java/com/artipie/docker/DockerProxy.java#L46-L49

The puzzle was created by @g4s8 on 15-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#338` is not assigned, can't get performer
