### ISSUE TITLE
A subdirectory inside repository storage with a name of repository should not be created

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#345]
A situation. A user have a binary repository:
__`repo.yml`__:
```yml
repo:
  type: file
  storage:
    type: fs
    path: /var/artipie/data
  permissions:
    "*":
      - "*"
```

And then he uploads a text.txt file to the repository. The structure of the storage dir will be the following:
```tree
├── data
│   └── repo
│       └── text.txt
```

A few days ago user decides to change the repository name to `my-repo.yaml`, while the configuration remains the same. The storage part still the same. Then he tries to reach the `text.txt` file, which was upload by the user a few days before:
```
$ curl -i  -X GET http://localhost:8080/my-repo/text.txt
HTTP/1.1 404 Not Found
Content-Length: 22
transfer-encoding: chunked

Key text.txt not found%
```

The attempt has failed, because for some reasons Artipie stores data in a subdirectory with a name equal to repository name; when repo name changes, the repository becomes empty and a user suffers from it.

If a user will try to upload the `text.txt` again he will create a duplicate in a neighbouring directory:
```
├── data
│   ├── my-repo
│   │   └── text.txt
│   └── repo
│       └── text.txt
```

I think that this behaviour is unacceptable. The data should be stored in the root of specified storage.

**Comment by g4s8** [comment]
@Sammers21 I don't agree on that: the repository storage should be isolated, and there should not be a way to have some shared data across repositories. It completely breaks authorization concept: if one user has permissions in `repo`, user should not be able to access any data from `repo2` repo without permissions.

Renaming could be an additional feature, where Artipie will handle all data movements in storage, so user will be able to rename repository without losing the data.

**Comment by Sammers21** [comment]
> It completely breaks authorization concept: if one user has permissions in repo, user should not be able to access any data from repo2 repo without permissions.

Explain it, please. Which authorization concept do you have in mind and how "keeping everything as is" breaks it?

**Comment by Sammers21** [comment]
> Renaming could be an additional feature, where Artipie will handle all data movements in storage, so user will be able to rename repository without losing the data.

Is there is painless for a user way to do it?

**Comment by g4s8** [comment]
@Sammers21 I mean it should not be possible to share the data for different repositories. I'd suggest to fix concrete usability issues. E.g. if you can't rename the repository - it's an issue, but the structure of directories inside the storage - it's implementation details. So we're not going to fix implementation details, only issues can be fixed.
