### ISSUE TITLE
Refactor class YamlSettings

### ISSUE THREAD

**Issue by amihaiemil** [artipie/artipie#35]
Inside class [YamlSettings](https://github.com/artipie/artipie/blob/554ae39602b5b0a60f6606cdc1e0760afba95a9d/src/main/java/com/artipie/YamlSettings.java#L38) there are the ``mapping()`` and ``string()`` methods which are basically checking for null values in the YamlMapping.

In the library ``eo-yaml`` there is the decorator [StrictYamlMapping](https://github.com/decorators-squad/eo-yaml/blob/67b8e462359372d36df2fee5e1c0775f115d2626/src/main/java/com/amihaiemil/eoyaml/StrictYamlMapping.java) which already performs those checks and complains about it.

I know because I wrote the library.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#35](https://github.com/artipie/artipie/issues/35) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/eaadd691-9a8c-4fb5-8c4b-2c9ffc232577); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@amihaiemil Looks like `StrictYamlMapping` is not compatible with another `YamlMapping` interface: it expects an `com.amihaiemil.eoyaml.AbstractYamlMapping`, which is not returned by the currently used methods (`Yaml.createYamlInput(input).readYamlMapping()` and `YamlMapping.yamlMapping()`).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@amihaiemil Merged, please close
