### ISSUE TITLE
Some repositories require root path to be supported

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#353]
Some repositories (e.g. pypi repo) requires the root path of repository to be supported, e.g. if repository is `central.artipie.com/foo/bar`, then `pip` tool may send request to `GET` for `central.artipie.com/foo/bar` to get repository index. But now we're serving dashboard pages on this location: `foo/bar` returns the dashboard page for repository `bar` of user `foo`.

Possible solutions:
 1. Use different routing schema, e.g. `/dashboard?repo=foo/bar` instead of `/foo/bar`
 2. Use [content negotiation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation) and return different content for different `Accept` headers (or `User-Agent` headers) if possible: `Accept: text/html` = browser request - returns dashboard page.

@artipie/contributors do you have some other ideas to fix it?

**Comment by olegmoz** [comment]
@g4s8 first option is better in my opinion, but I'd put repo name into path like `/dashboard/foo/bar`

**Comment by olenagerasimova** [comment]
@g4s8 I've checked my dashboard and created new repos without any problems, can we close this?

**Comment by g4s8** [comment]
@olenagerasimova yes, thanks
