### ISSUE TITLE
Trim repo name from Docker image name when stored

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#371]
Docker adapter release `0.3.1` supports `TrimmedDocker` that cuts specified prefix in repo names when they are stored or loaded from storage. `TrimmedDocker` should be used to wrap underlying `Docker` instance both in for `docker` and `docker-proxy` repo types with prefix being repo name.

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#371` is not assigned, can't get performer
