### ISSUE TITLE
Docker: Performance issues

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#381]
![image](https://user-images.githubusercontent.com/16746106/88254452-0ea88880-ccbe-11ea-8098-a3f4bb93fc81.png)

![image](https://user-images.githubusercontent.com/16746106/88254444-06504d80-ccbe-11ea-9985-dc040724c435.png)

Looks like latest [docker registry](https://docs.docker.com/registry/) performs a way better then Artipie. @yegor256 think that we should improve the situation.

A script, which were used to perform benchmarking available here: https://gist.github.com/Sammers21/5bf2ab0d93d258a64fca4fbdd1f70339

**Comment by g4s8** [comment]
@Sammers21 it's the same bug as #382, closing as duplicate.

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#381` is not assigned, can't get performer
