### ISSUE TITLE
Python simple repository support

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#387]
Update pypi-adapter version to 0.5.4 to add python simple repository support.

**Comment by olenagerasimova** [comment]
@0crat assign me

**Comment by 0crat** [comment]
Job was finished in 16 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by g4s8** [comment]
@rultor release, tag=`0.9`
