### ISSUE TITLE
Artipie distribution 

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#40]
It should be possible to install artipie on almost any platform and obtain as:

- [ ] a `.rpm`/`.deb`  package available for major Linux distributions via dnf/apt/yum package managers
- [ ]  a brew package for Mac OS X
- [x] a docker container (#41)
- [x] a fat`.jar` file

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
@Sammers21 the puzzle [#46](https://github.com/artipie/artipie/issues/46) is still not solved.

**Comment by 0pdd** [comment]
@Sammers21 the only puzzle [#46](https://github.com/artipie/artipie/issues/46) is solved here.

**Comment by olenagerasimova** [comment]
fat .jar is available in github releases, docker image is available in docker hub, no other distribution packages will be added
