### ISSUE TITLE
Artipie distributed in docker containers

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#41]
- [x] Create a docker file for artipie(#43)
- [x] Deploy a container to Docker Hub via Github Actions(#44)
- [x] Update readme in accordance with the change

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@Sammers21 let's discuss JDK version and base image version before start

**Comment by Sammers21** [comment]
@g4s8, i would suggest to use jre 13 image, based on alpine.

**Comment by g4s8** [comment]
@Sammers21 all fixed

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#41` is not assigned, can't get performer
