### ISSUE TITLE
Add Artifactory create repo API

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#413]
Support Artifactory API for creating a new repository, the endpoint should accept `PUT /api/repositories/{repoKey}` requests as in https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API and accepts JSON https://www.jfrog.com/confluence/display/JFROG/Repository+Configuration+JSON
From this JSON we should support these fields:
 - `key` - repository name
 - `rclass` - support `local`
 - `packageType` - support `docker`
 - `dockerApiVersion` - should be `V2`

This `PUT` request creates a new YAML config in repo config storage.
New repository should use `default` storage alias.

**Comment by olenagerasimova** [comment]
@g4s8 what response status should be returned in case of success?

**Comment by g4s8** [comment]
@olenagerasimova I suppose Artifactory returns `200` on success. Also, please pay attention:
> If a repository with the specified repoKey already exists, the call fails with a 400 response.

and we need to perform authentication for such requests.
