### ISSUE TITLE
PR Number #412 broke maven repositories

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#419]
Build after the PR merge: https://github.com/artipie/artipie/runs/949411623|
Build before the PR merge: https://github.com/artipie/artipie/runs/949351161

Also I've tried to run the maven proof locally and the progress stuck at:
```
[INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ sample-for-deployment ---
Uploading to artipie: http://localhost:8080/my-maven/com/artipie/sample-for-deployment/1.0/sample-for-deployment-1.0.jar
Progress (1): 1.6 kB
```

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#419` is not assigned, can't get performer
