### ISSUE TITLE
Get rid of properties

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#42]
For now, properties are passed in the following way:
```
-Dartipie.storage=./config.yml -Dartipie.port=8080
```
That is not gonna work in case is compiled as a native image. We should move to command line args

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@Sammers21 it's a duplicate of #32

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#42` is not assigned, can't get performer
