### ISSUE TITLE
Helm proof is broken

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#423]
When data is being posted to helm repo, the 100 response is started to being printed and then stuck. Try helm proof for details:

```
curl -i -X POST --data-binary @tomcat-0.4.1.tgz http://localhost:8080/example_helm_repo/
HTTP/1.1 100 Continue

```

**Comment by g4s8** [comment]
@Sammers21 does `curl -i -X POST --data-binary @tomcat-0.4.1.tgz http://localhost:8080/example_helm_repo/` command sends `Expect: 100-Continue` header? Please check it with verbose output

**Comment by Sammers21** [comment]
@g4s8, no it does not:
```
$  curl -v -i -X POST --data-binary @tomcat-0.4.1.tgz http://localhost:8080/example_helm_repo/
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST /example_helm_repo/ HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 4051
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
HTTP/1.1 100 Continue

* We are completely uploaded and fine

```

**Comment by g4s8** [comment]
@Sammers21 according to your logs it sends it: `> Expect: 100-continue`, so `100 Continue` response is correct for this request

**Comment by Sammers21** [comment]
@g4s8, why does is stuck then? I guess that the response end line is not received and curl waits for it to arrive.

**Comment by Sammers21** [comment]
@g4s8, If we would set a timeout for the request:

```
curl -v -i -X POST -m 10 --data-binary @tomcat-0.4.1.tgz http://localhost:8080/example_helm_repo/
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST /example_helm_repo/ HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 4051
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
HTTP/1.1 100 Continue

* We are completely uploaded and fine
* Operation timed out after 10004 milliseconds with 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 10004 milliseconds with 0 bytes received

~/Git/artipie/examples/helm on  reliable_proofs! ⌚ 13:29:45
$  curl -v -i -X POST --max-time 10 --data-binary @tomcat-0.4.1.tgz http://localhost:8080/example_helm_repo/
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST /example_helm_repo/ HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 4051
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
HTTP/1.1 100 Continue

* We are completely uploaded and fine
* Operation timed out after 10004 milliseconds with 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 10004 milliseconds with 0 bytes received
```

The timeout error will be thrown

**Comment by g4s8** [comment]
@Sammers21 it seems the script for testing helm is broken byself, see my output for that:
```
++ set -e
+++ pwd
+++ pwd
++ docker run --rm -d --name artipie -it -v /home/g4s8/projects/github.com/artipie/artipie/examples/helm/artipie.yaml:/etc/artipie.yml -v /home/g4s8/projects/github.com/artipie/artipie/examples/helm:/var/artipie -p 8080:80 artipie/artipie:latest
7e27a258b357641c5a80771e02b5aef85e3bb50f821fae611ac86a8db1f81385
++ sleep 5
++ curl -i -X POST --data-binary @tomcat-0.4.1.tgz http://localhost:8080/example_helm_repo/
HTTP/1.1 405 Method Not Allowed
transfer-encoding: chunked

++ helm repo add artipie_example_repo http://localhost:8080/example_helm_repo/
Error: Looks like "http://localhost:8080/example_helm_repo/" is not a valid chart repository or cannot be reached: Failed to fetch http://localhost:8080/example_helm_repo/index.yaml : 404 Not Found
```

**Comment by Sammers21** [comment]
@g4s8, helm repo add does not work because index.yaml wasn't generated. It is generates when you post a package.

**Comment by Sammers21** [comment]
@g4s8, look at the history of helm proof: 
![image](https://user-images.githubusercontent.com/16746106/89544287-9b009280-d80a-11ea-9efd-fd055c5dc499.png)

**Comment by g4s8** [comment]
@Sammers21 but when I post a package using `curl` helm repo responds me with `405 - METHOD_NOT_ALLOWED`, so I just can't reproduce it with `run.sh`

**Comment by Sammers21** [comment]
@g4s8, can you try `b94f28a65b8c707215029be86a852449e89bea4f` commit?

**Comment by Sammers21** [comment]
@g4s8, that is what i'm getting on this commit: 
```
+ curl -i -X POST --data-binary @tomcat-0.4.1.tgz http://localhost:8080/example_helm_repo/
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
transfer-encoding: chunked

+ helm repo add artipie_example_repo http://localhost:8080/example_helm_repo/
"artipie_example_repo" has been added to your repositories
+ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "artipie_example_repo" chart repository
Update Complete. ⎈ Happy Helming!⎈
```

**Comment by Sammers21** [comment]
@g4s8, This commit is exactly one merge before the current `master` state.

> @g4s8, can you try `b94f28a65b8c707215029be86a852449e89bea4f` commit?

**Comment by g4s8** [comment]
@Sammers21 so I don't get the problem: I can't reproduce the issue with `100 Continue` response instead of expected because I can't run the script in master because of `METHOD_NOT_ALLOWED` response. I think this bug is not valid if it can't be reproduced in latest commit in master

**Comment by Sammers21** [comment]
@g4s8, The problems consistently reproduces on Github actions and on my machine locally. 

> @Sammers21 so I don't get the problem: I can't reproduce the issue with `100 Continue` response instead of expected because I can't run the script in master because of `METHOD_NOT_ALLOWED` response. I think this bug is not valid if it can't be reproduced in latest commit in master

**Comment by Sammers21** [comment]
@g4s8, I think something wrong with the #412 PR. Can you please revert it, then we turn proofs on, and then we will have time figure out?

**Comment by g4s8** [comment]
@Sammers21 no I can't revert it, because it's important and fixes critical bug.

> if you can share the actions you take that would be awesome.

 1. I pulled the latest commit from `master` branch
 2. Changed directory to `./examples/helm/`
 3. Started `./run.sh` script

**Comment by Sammers21** [comment]
@g4s8, the script uses `artipie/artipie:latest` image, that why you are getting this result. Build docker image on the latest branch and replace `artipie/artipie:latest` with it.

**Comment by g4s8** [comment]
@Sammers21 thanks. I just run this script using the latest local Docker image from `HEAD` commit in `master` and it's working fine:
```
++ set -e
+++ pwd
+++ pwd
++ docker run --rm -d --name artipie -it -v /home/g4s8/projects/github.com/artipie/artipie/examples/helm/artipie.yaml:/etc/artipie.yml -v /home/g4s8/projects/github.com/artipie/artipie/examples/helm:/var/artipie -p 8080:80 artipie.local
d3fb655143357bf86d2bb69e62787ffbc5e0c5eff641ce07d5c34b2682f7a5cf
++ sleep 5
++ curl -i -X POST --data-binary @tomcat-0.4.1.tgz http://localhost:8080/example_helm_repo/
HTTP/1.1 200 OK
transfer-encoding: chunked

++ helm repo add artipie_example_repo http://localhost:8080/example_helm_repo/
"artipie_example_repo" has been added to your repositories
++ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "artipie_example_repo" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
++ docker stop artipie
artipie
```

Can you please specify where exactly was origin error?

**Comment by Sammers21** [comment]
@g4s8, what is the commit number?

> @Sammers21 thanks. I just run this script using the latest local Docker image from `HEAD` commit in `master` and it's working fine:
> 
> ```
> ++ set -e
> +++ pwd
> +++ pwd
> ++ docker run --rm -d --name artipie -it -v /home/g4s8/projects/github.com/artipie/artipie/examples/helm/artipie.yaml:/etc/artipie.yml -v /home/g4s8/projects/github.com/artipie/artipie/examples/helm:/var/artipie -p 8080:80 artipie.local
> d3fb655143357bf86d2bb69e62787ffbc5e0c5eff641ce07d5c34b2682f7a5cf
> ++ sleep 5
> ++ curl -i -X POST --data-binary @tomcat-0.4.1.tgz http://localhost:8080/example_helm_repo/
> HTTP/1.1 200 OK
> transfer-encoding: chunked
> 
> ++ helm repo add artipie_example_repo http://localhost:8080/example_helm_repo/
> "artipie_example_repo" has been added to your repositories
> ++ helm repo update
> Hang tight while we grab the latest from your chart repositories...
> ...Skip local chart repository
> ...Successfully got an update from the "artipie_example_repo" chart repository
> ...Successfully got an update from the "jetstack" chart repository
> ...Successfully got an update from the "stable" chart repository
> Update Complete.
> ++ docker stop artipie
> artipie
> ```
> 
> Can you please specify where exactly was origin error?

**Comment by Sammers21** [comment]
Works for me too. Error still present on CI.

**Comment by g4s8** [comment]
@Sammers21 please check #423 PR with fix.

**Comment by Sammers21** [comment]
I can't reproduce the error:
```
+ curl -i -v -X POST -H 'Expect: 100-continue' --data-binary @tomcat-0.4.1.tgz http://localhost:8080/example_helm_repo/
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST /example_helm_repo/ HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> Expect: 100-continue
> Content-Length: 4051
> Content-Type: application/x-www-form-urlencoded
>
< HTTP/1.1 100 Continue
HTTP/1.1 100 Continue

* We are completely uploaded and fine
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< transfer-encoding: chunked
transfer-encoding: chunked

<
* Connection #0 to host localhost left intact
* Closing connection 0
+ helm repo add artipie_example_repo http://localhost:8080/example_helm_repo/
"artipie_example_repo" has been added to your repositories
+ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "artipie_example_repo" chart repository
Update Complete. ⎈ Happy Helming!⎈
```

Commit: f896f52702228a8ea32a248c3c57130cf2b6cd3f

**Comment by Sammers21** [comment]
> @Sammers21 please check #423 PR with fix.

Is it possible to make sure that helm and maven proofs are passing before merging the PR?

**Comment by 0crat** [comment]
Job was finished in 39 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
