### ISSUE TITLE
Integrate HTTP client

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#429]
To start migration of Artipie to abstract HTTP client module it should be added as dependency and be available when `Pie` is created. For now adapters that are not using HTTP client module may access it's Jetty client directly.

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#434](https://github.com/artipie/artipie/issues/434) is still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#429` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@olegmoz the only puzzle [#434](https://github.com/artipie/artipie/issues/434) is solved here.
