### ISSUE TITLE
Gradle client: not able to find dependencies (same works fine with maven)

### ISSUE THREAD

**Issue by akuleshov7** [artipie/artipie#445]
## How to reproduce:

Use simple build.gradle from diktat project:
`$ git clone https://github.com/cqfn/diKTat.git`

run 
`$ gradle ktlint`

## Issue
```
* What went wrong:
Execution failed for task ':ktlint'.
> Could not resolve all files for configuration ':ktlint'.
   > Could not find com.pinterest:ktlint:0.37.1-fork.
     Searched in the following locations:
       - https://central.artipie.com/akuleshov7/diktat/com/pinterest/ktlint/0.37.1-fork/ktlint-0.37.1-fork.pom
       - https://repo.maven.apache.org/maven2/com/pinterest/ktlint/0.37.1-fork/ktlint-0.37.1-fork.pom
       - https://jcenter.bintray.com/com/pinterest/ktlint/0.37.1-fork/ktlint-0.37.1-fork.pom
     Required by:
         project :

```

But the file https://central.artipie.com/akuleshov7/diktat/com/pinterest/ktlint/0.37.1-fork/ktlint-0.37.1-fork.pom exists and everything works fine with maven

## Extra info
In the file I can some strange information:
https://central.artipie.com/akuleshov7/diktat/com/pinterest/ktlint/0.37.1-fork/ktlint-0.37.1-fork.pom

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
