### ISSUE TITLE
http GET api health endpoint

### ISSUE THREAD

**Issue by jeffzhu503** [artipie/artipie#448]
The artipie server must have the endpoint for the health status. If the return code is not 200, we must send the alert to the monitoring system users have. 

Something like this: 
/health:
    get:
      summary: 'Health check API'
      description: |
        The endpoint returns the health stauts of the system.
      tags:
        - Products
      responses:
        '200':
          description: The system health status.
        '40x': for any possible error

**Comment by olegmoz** [comment]
Health check endpoint was added to Artpie in PR https://github.com/artipie/artipie/pull/458 see  https://github.com/artipie/artipie/issues/392

@jeffzhu503 may we close this issue?

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#448` is not assigned, can't get performer
