### ISSUE TITLE
Add integration tests for Docker

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#449]
Right now end-to-end integration tests are missing from Artipie, which allows to introduce breaking changes to repositories functionality. In particular such tests are missing for `docker` and `docker-proxy` repository types. This test are need to be sure that these repositories are always functional

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#470](https://github.com/artipie/artipie/issues/470) is still not solved.

**Comment by 0pdd** [comment]
@olegmoz 2 puzzles [#470](https://github.com/artipie/artipie/issues/470), [#493](https://github.com/artipie/artipie/issues/493) are still not solved.

**Comment by 0pdd** [comment]
@olegmoz 3 puzzles [#470](https://github.com/artipie/artipie/issues/470), [#493](https://github.com/artipie/artipie/issues/493), [#512](https://github.com/artipie/artipie/issues/512) are still not solved.

**Comment by 0pdd** [comment]
@olegmoz 2 puzzles [#470](https://github.com/artipie/artipie/issues/470), [#512](https://github.com/artipie/artipie/issues/512) are still not solved; solved: [#493](https://github.com/artipie/artipie/issues/493).

**Comment by 0pdd** [comment]
@olegmoz 3 puzzles [#470](https://github.com/artipie/artipie/issues/470), [#512](https://github.com/artipie/artipie/issues/512), [#524](https://github.com/artipie/artipie/issues/524) are still not solved; solved: [#493](https://github.com/artipie/artipie/issues/493).

**Comment by olegmoz** [comment]
Closed by #523

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#449` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@olegmoz 2 puzzles [#470](https://github.com/artipie/artipie/issues/470), [#512](https://github.com/artipie/artipie/issues/512) are still not solved; solved: [#493](https://github.com/artipie/artipie/issues/493), [#524](https://github.com/artipie/artipie/issues/524).

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#512](https://github.com/artipie/artipie/issues/512) is still not solved; solved: [#470](https://github.com/artipie/artipie/issues/470), [#493](https://github.com/artipie/artipie/issues/493), [#524](https://github.com/artipie/artipie/issues/524).
