### ISSUE TITLE
Replace `ChainedAuth` with `Authentication.Joined`

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#454]
`Authentication.Joined` class will be added soon to HTTP module. It's functionality is similar to `ChainedAuth` used in Artpie. After release of HTTP with `Authentication.Joined` it is going to be possible to replace `ChainedAuth` with `Authentication.Joined`.

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
