### ISSUE TITLE
Proofs should not run tests

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#466]
Building Artipie in proofs involves running all the tests and other verification. That makes these workflows run longer and be more prone to errors, issue #465 is an example

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#466` is not assigned, can't get performer
