### ISSUE TITLE
Add NPM adapter

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#47]
Support NPM adapter as Artipie module

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by 0crat** [comment]
The job [#47](https://github.com/artipie/artipie/issues/47) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f295bbd1-adab-4d7a-a6a7-c99c0418a7fb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job
