### ISSUE TITLE
DeleteUserSlice.java:45-50: Create class...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#484]
The puzzle `444-f6623627` from #444 has to be resolved: 

https://github.com/artipie/artipie/blob/b9556efd74d646913a3caed41a059088d4d80245/src/main/java/com/artipie/api/artifactory/DeleteUserSlice.java#L45-L50

The puzzle was created by Alexandr on 21-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#484` is not assigned, can't get performer
