### ISSUE TITLE
DockerLocalIT.java:47-51: Support running test on...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#493]
The puzzle `449-81c7f5cc` from #449 has to be resolved: 

https://github.com/artipie/artipie/blob/df85be7b575385b40f9f0f42f395067bf6ff3d4a/src/test/java/com/artipie/docker/DockerLocalIT.java#L47-L51

The puzzle was created by Oleg Mozzhechkov on 21-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#493` is not assigned, can't get performer
