### ISSUE TITLE
Remove "layout: flat" from proofs and examples

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#499]
Layout should be made optional for configuration using `flat` value by default. With this done `layout: flat` could be removed from all proofs and examples

**Comment by 0pdd** [comment]
@olegmoz 2 puzzles [#510](https://github.com/artipie/artipie/issues/510), [#511](https://github.com/artipie/artipie/issues/511) are still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#499` is not assigned, can't get performer

**Comment by olegmoz** [comment]
The issue is not solved, the PRs were unrelated and were bound to the issue by mistake

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olegmoz** [comment]
@IlyaMoskva the PRs mentioned in the issue are all unrelated, and bound to the issue by mistake. There was no any work done on this issue

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#499` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#510](https://github.com/artipie/artipie/issues/510) is still not solved; solved: [#511](https://github.com/artipie/artipie/issues/511).
