### ISSUE TITLE
Nuget adapter does not work because of jar hell

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#503]
He jcabi-xml 0.20.4 version is used, while expected is 0.22.2

As a result, the following exception is thrown:
![image](https://user-images.githubusercontent.com/16746106/91192757-fb466e00-e6fe-11ea-8b95-6988949d0e14.png)

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#503` is not assigned, can't get performer
