### ISSUE TITLE
GetPermissionSliceTest.java:55-58: Create class to...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#509]
The puzzle `495-a27c3b37` from #495 has to be resolved: 

https://github.com/artipie/artipie/blob/edebc7f1eefaa3068b72ea7a635a411027bd7540/src/test/java/com/artipie/api/artifactory/GetPermissionSliceTest.java#L55-L58

The puzzle was created by olenagerasimova on 25-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
You @genryxy[/z](https://www.0crat.com/u/genryxy) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#509` is not assigned, can't get performer
