### ISSUE TITLE
Refactor PermissionSlices

### ISSUE THREAD

**Issue by genryxy** [artipie/artipie#515]
Create class `RepoFromRqLine`. 
Logic for getting repo from request line is the same in 3 classes: `DeletePermissionSlice`, `GetPermissionSlice` and in `AddUpdatePermissionSlice`. It would be nice to introduce class to obtain repo from request line and move `GetPermissionSlice.PTRN`  there.

**Comment by olenagerasimova** [comment]
@genryxy may add a suggestion here? If we introduce class `RepoFromRqLine` the code inside it will be the same as in `UserFromRqLine`, only regular expressions will differ. Let's rename `UserFromRqLine` to `FromRqLine` and add field `Pattern` with pattern to match request line by. 
Also, I'd suggest to keep regexs for usernames and repo name in `FromRqLine` only (as public constants) and remove them from slices.

**Comment by genryxy** [comment]
@olenagerasimova yeah, it's a good suggestion.
