### ISSUE TITLE
Docker repositories do not work with authentication

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#521]
When Docker client tries to perform an operation it first sends `GET /v2/` request. Response to this request should contain version header and `WWW-Authenticate` header if needed. Now Artipie always sends empty `200 OK` response for this endpoint. This behavior is implemented in `DockerRoutingSlice`. It works well in scenarios when authentication is not required. But when auth is required for other endpoints client does not receive `WWW-Authenticate` and does not tries to authenticate for any other requests. So in practice authenticated access does not work for Docker repositories.

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project
