### ISSUE TITLE
Maven integration tests

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#535]
Part of #389 Let's add an integration test similar to https://github.com/artipie/artipie/issues/449 to verify Maven repository:
 - Deploy and download release artifact
 - Deploy and download snapshot artifact
 - Download and cache artifact using remote proxy Maven slice

It can be implemented using `org.eclipse.aether` classes similar to https://github.com/artipie/maven-adapter/blob/master/src/test/java/com/artipie/maven/MavenHttpITCase.java

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @g4s8[/z](https://www.0crat.com/u/g4s8) (its creator); I won't close the order; please, re-open it and ask @g4s8[/z](https://www.0crat.com/u/g4s8) to close it
