### ISSUE TITLE
Global permissions support

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#544]
Now Artipie supports configuration of permissions on per repository level. So it is impossible to give permissions to multiple or all repositories to a user in one place. For that we need to implement global permissions with wildcard support, so it would be possible to give a user permission for all operation in repository `repoA/**/*` or do anything in all repositories `**`.

**Comment by olegmoz** [comment]
When global permissions are added to the application we have two permission rules: global and repo level. This means for any given request from user the rules need to be combined. Here is the table, that seems to be reasonable for this composition:

Global | Repo | Result
------- | ------- | -------
absent | absent | allow
absent | allow | allow
absent | deny | deny 
allow | absent | allow
allow  | allow | allow
allow | deny | allow
deny | absent | deny
deny  | allow | allow
deny | deny | deny

This behavior preserves behavior of repo level permissions as-is in absence of global permissions, and global permissions work as-is in absence of repo level permissions. When combined action is allowed when any of levels allow

**Comment by olegmoz** [comment]
It seems that after all we do not need global permissions support

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#544` is not assigned, can't get performer
