### ISSUE TITLE
Add Conan adapter

### ISSUE THREAD

**Issue by aiovlev** [artipie/artipie#553]
Support conan C/C++ packages
- [x] Conan packages download (V1 & V2 API)
- [x] Conan packages upload
- [x] Users auth. & permissions
- [ ] Support for custom package channels
- [ ] Errors\exceptions handling: verbose error message to client & logs and more tests for corner-cases.

**Comment by olegmoz** [comment]
@aiovlev thanks, Conan looks to be quite popular packages repository. Cannot find any docs regarding it's server API, do you know if there is such documentation with endpoints description?

**Comment by aiovlev** [comment]
@olegmoz , I didn't find too. :( But you can look on implementation in the opensource conan-server (python): https://github.com/conan-io/conan/blob/develop/conans/server/rest/controller/v2/conan.py

**Comment by g4s8** [comment]
@aiovlev we created a task for Conan local repository: https://github.com/artipie/conan-adapter/issues/1, when ready we'll integrate it to Artipie.

**Comment by ChGen** [comment]
Conan adapter currently in development:
https://github.com/artipie/conan-adapter

**Comment by ChGen** [comment]
Current status:
* Readme file was updated.
* Conan repo SDK - Java APIs for Conan V2 revisions index support is added.
* Conan HTTP API - added support for HTTP V1 & V2 API (download & basic search).

**Comment by ChGen** [comment]
Current status:
Done:
* Basic conan packages uploading support
* Added integration tests
* Published conan-adapter v0.2 release.

TODO:
* Users auth. & permissions
* Support for custom package channels
* Errors\exceptions handling: verbose error message to client & logs and more tests on corner-cases

**Comment by ChGen** [comment]
Current status:
Done:
* Users authentication and permissions support
* Updated conan and dependencies versions
* Published conan-adapter v0.3.0 release.

TODO:
* Support for custom package channels
* Errors\exceptions handling: verbose error message to client & logs and more tests on corner-cases

**Comment by ChGen** [comment]
Actually, Conan adapter currently added and integrated in Artipie project. It supports conan 1.x. Further work will be in https://github.com/artipie/artipie/issues/1342
