### ISSUE TITLE
Create readme section about Artifactory API support

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#555]
Artipie implements parts of Artifactory API and plans to support more of endpoints. This feature is not covered in documentation. Established features and features required in future should be described, so they will be visible to users migrating from Artifactory.

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#555` is not assigned, can't get performer
