### ISSUE TITLE
Failed to run docker "could not load main class"

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#56]
I tried to start docker image from latest master with commands:
```bash
docker build -t artipie:local .
docker run -v /tmp/artipie:/artipie/repositories artipie:local
```
And got an error:
```
Error: Could not find or load main class com.artipie.Main
Caused by: java.lang.ClassNotFoundException: com.artipie.Main
```
Docker image should find main class correctly.

**Comment by 0crat** [comment]
The job [#56](https://github.com/artipie/artipie/issues/56) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/444a8b5d-adc9-4042-a136-b6a015227c3d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @sammers21[/z](https://www.0crat.com/u/sammers21) resigned from [#56](https://github.com/artipie/artipie/issues/56), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#56](https://github.com/artipie/artipie/issues/56) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/c0b37114-f5bd-4d6f-a6d8-0b1b33975e64); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@g4s8 I tried with latest master and it works. There are other errors though about the storage not being configured.

**Comment by victornoel** [comment]
@0crat wait for submitter answer

**Comment by victornoel** [comment]
@g4s8 I can fix it if it enters the scope of this issue

**Comment by g4s8** [comment]
@victornoel I suppose it's fixed. Please report another bugs with steps to reproduce as new tickets

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#56` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/56#issuecomment-609715761))

@g4s8 The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#56](https://github.com/artipie/artipie/issues/56), please stop working. Reason for job resignation: Order was cancelled
