### ISSUE TITLE
Artifactory permissions API: return 404 when repo does not exist

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#565]
`DeletePermissionSlice` and `GetPermissionSlice` should return 404 if requested permissions target (repository) does not exist. Such behavior is not directly documented by artifactory, but I think it would be more correct than return 500 as we do now.
Also let's correct `AddUpdatePermissionSlice` javadoc.

**Comment by olenagerasimova** [comment]
@olegmoz what do you think?

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it
