### ISSUE TITLE
User groups support

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#573]
We should implement support for groups, so users may be assigned to multiple groups and some permissions may be granted to whole group and not individual users

One example is `readers` group, see https://github.com/artipie/artipie/issues/572

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olenagerasimova** [comment]
@olegmoz hm, I think we can close this ticket as we support groups for users now and I continue my work on readers group support and part of #572

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#573` is not assigned, can't get performer
