### ISSUE TITLE
Permission aliases in HTTP API

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#574]
In permissions API we need to support short aliases for permissions, `r` for read or download operations, `w` for write or upload operations

**Comment by olenagerasimova** [comment]
@olegmoz as we agreed today the most suitable and universal way here is to support some kind of synonyms set for "read" and "write", so here is what I'm planning to do:
1. In http create enum with permissions `READ` and `WRITE` and varargs field for synonyms, create class to obtain enum instance by any string synonym 
2. Change `Permission.ByName` string `action` field to enum and add new ctor, use a set of synonyms to call `Permissions#allowed` with from the `Permission.ByName#allowed`
3. Change `AddUpdatePermissionSlice` to convert all possible sent permissions to `read` and `write` before saving them to config
4. Change `GetPermissionSlice` to convert all possible actions names from config (including asterisk as artifactory does not support it) to `read` and `write` before returning them

As far as I see first two steps should save us from changing anything in the adapters, I do not see any problems with docker either. 
Any thoughts here?

**Comment by olegmoz** [comment]
@olenagerasimova design you propose sounds good, but I would not use enum for permission and create some interface instead. This will allow us to create custom permissions dynamically. For example we may need a read permissions for certain path, this cannot be done with enum.

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) resigned from [#574](https://github.com/artipie/artipie/issues/574), since the job is not in scope anymore
