### ISSUE TITLE
Extract class for layout

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#586]
Now `layout` is represented with `String` in `Settings`. In many places the values is read and handled manually according to value `org` or `flat`. These two types of layout could be extracted to classes with same interface that parses repo name from URI and does other required operations

**Comment by 0pdd** [comment]
@olegmoz 2 puzzles [#788](https://github.com/artipie/artipie/issues/788), [#789](https://github.com/artipie/artipie/issues/789) are still not solved.

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#789](https://github.com/artipie/artipie/issues/789) is still not solved; solved: [#788](https://github.com/artipie/artipie/issues/788).

**Comment by 0pdd** [comment]
@olegmoz all 2 puzzles are solved here: [#788](https://github.com/artipie/artipie/issues/788), [#789](https://github.com/artipie/artipie/issues/789).
