### ISSUE TITLE
artipie module still depends on old ppom

### ISSUE THREAD

**Issue by victornoel** [artipie/artipie#59]
I suppose this is a mistake, I noticed all other projects are depending on ppom 0.3 but artipie module depends on ppom 0.2.1 and my IDE sets it up with Java 11 instead of Java 8.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@victornoel thanks, should be fixed now:

**Comment by victornoel** [comment]
@g4s8 I'm confused, I thought artipie is meant to be built with Java 8, not Java 11.

My initial problem was that in my IDE, artipie module uses Java 11 while for example rpm-adapter uses Java 8.

I would have expected now that they would use the same version, but in your commit you confirmed the use of Java 11.

Am I missing something?

**Comment by g4s8** [comment]
@victornoel add `*-adapter` modules can be used in two ways:
 - to generate metadata for existing binary artifacts (e.g. `rpm-adapter` and `npm-adapter` are used in such way), e.g. `new Rpm(path).update("package.rpm")` will update metadata for files. So we need to use lower JDK version to support more users
 - provides HTTP API for repository, it can be used  by artipie/artipie server iself

The artipie/artipie module can't be used as a dependency, this is why we don't have such restrictions in JDK version and can use higher version (11 is the highest LTS version now). So this module uses 11 JDK, but all adapters uses 1.8 version.

**Comment by victornoel** [comment]
@g4s8 perfect, this is clear now, thank you!

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#59` is not assigned, can't get performer
