### ISSUE TITLE
Update go-adapter

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#601]
Let's bump go-adapter version and add pass users and auth there.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it
