### ISSUE TITLE
NuGet integration tests

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#602]
Add integration tests that verify that NuGet can upload and install packages with authentication enabled and disabled.
Such integration tests are present in NuGet adapter repository

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olegmoz** [comment]
It is problematic to test authentication for NuGet, see https://github.com/artipie/artipie/issues/657

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#677](https://github.com/artipie/artipie/issues/677) is still not solved.

**Comment by 0pdd** [comment]
@olegmoz 2 puzzles [#677](https://github.com/artipie/artipie/issues/677), [#679](https://github.com/artipie/artipie/issues/679) are still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#602` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@olegmoz all 2 puzzles are solved here: [#677](https://github.com/artipie/artipie/issues/677), [#679](https://github.com/artipie/artipie/issues/679).
