### ISSUE TITLE
Files repository integration tests

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#603]
Add integration tests that verify that Curl can upload and download binary files with authentication enabled and disabled

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#603` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@genryxy it looks like we have all the tests needed: upload, download and auth coverage. I think we are ready to close the issue or we are missing something?

**Comment by genryxy** [comment]
@olegmoz yeah, this question can be closed
