### ISSUE TITLE
NPM local integration tests

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#605]
Add integration tests that verify that NPM can upload and install packages with authentication enabled and disabled

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#605` is not assigned, can't get performer
