### ISSUE TITLE
Helm integration tests

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#607]
Add integration tests that verify that Helm can upload and install packages with authentication enabled and disabled.
Such integration tests are present in Helm adapter repository

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#791](https://github.com/artipie/artipie/issues/791) is still not solved.
