### ISSUE TITLE
Document how to configure maven-proxy with authentication

### ISSUE THREAD

**Issue by ilx** [artipie/artipie#608]
I would like to proxy private nexus/artifactory proxy. It is not evident to me how to configure such maven proxy from the current documentation/tests/samples.

**Comment by olegmoz** [comment]
@ilx thank you pointing this out, but we do not have support for that yet. We are going to support authentication for remote proxies in coming months

**Comment by ilx** [comment]
@olegmoz Thank you for information. I liked the idea of the project. Keep up!

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#608` is not assigned, can't get performer
