### ISSUE TITLE
Unable to start docker image

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#61]
When starting new docker image I'm getting an error:
```
Exception in thread "main" APP main com.artipie.VertxMain: Using default port: 80
java.lang.IllegalStateException: Storage is not configured
	at com.artipie.VertxMain.main(VertxMain.java:108)
```

**Comment by 0crat** [comment]
The job [#61](https://github.com/artipie/artipie/issues/61) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/93a1bb3d-7b52-4360-a944-1a42bec34eaa); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
Fixed by https://github.com/g4s8/artipie/commit/1c46cc19a9099f0eac34bd4a13dfa1379b10f3b1

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
