### ISSUE TITLE
Extract common code for repositories operations

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#622]
There are multiple places in code where list of repositories is read from storage, single repository is added or read from storage. Still there is not class that represents repositories of Artipie or single repository, so the code keeps copied from place to place. This has to be resoled with creating required abstractions and using them in Artipie.

**Comment by olenagerasimova** [comment]
This issue is not valid, as we introduced several classes to deal with storages settings: `ArtipieRepositories`, `ConfigFile`, `ConfigFileApi`. Now the only place where we obtain collection of repositories is `VertxMain`, repository settings are updated by `ConfigFileApi`.
