### ISSUE TITLE
Respond with 404 to request not related to repositories

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#633]
`SliceByPath` should not crash, but respond with `404` for requests that cannot be directed to a repository, such as `/favicon.ico` or `robots.txt` for example

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#633` is not assigned, can't get performer
