### ISSUE TITLE
Test log is huge

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#634]
For now, debug logs are enabled for `com.artipie` package, which results in a monstrous size build logs. It's even not possible to go to the end of this log because GitHub actions interface simply unable to show it.

I'd like to suggest to disable those debugs logs by default. Of course, they could be enabled during an investigation. But for default CI run it's too much.

**Comment by olegmoz** [comment]
Solved in #637

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#634` is not assigned, can't get performer
