### ISSUE TITLE
Too much details about storage operation in logs

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#637]
When run in production or for purpose of integration testing too much log output is provided by `MeasuredStorage`. To reduce amount of log messages printed it's logging level should be configurable with being trace by default

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#637` is not assigned, can't get performer
