### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by victornoel** [artipie/artipie#64]
The README seems outdated:
- it's referring to old ways of configuring artipe using system properties in the "How to start" section
  - instead of using CLI options
- it is missing instructions to build the docker image
- it contains duplicate information between "Setup the server" and "Configuration" sections

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#64](https://github.com/artipie/artipie/issues/64) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/7a6ba9e7-6e91-43c3-9d04-43158bf9a75b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@victornoel please check https://github.com/artipie/artipie/commit/ed83b89f7c3772655d8ee5edfe16f7270e7d4366
it should be fixed now

**Comment by g4s8** [comment]
@0crat assign me

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/artipie/issues/64#issuecomment-612049618))

@victornoel This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#64](https://github.com/artipie/artipie/issues/64) is [in scope](http://www.zerocracy.com/policy.html#14) for 4days
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [4days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fartipie%2364%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@g4s8 thx
