### ISSUE TITLE
Quick start problem

### ISSUE THREAD

**Issue by vongosling** [artipie/artipie#646]
1. maven-adapter version 0.4.10 is not in the maven center repo. -  https://search.maven.org/artifact/com.artipie/maven-adapter
2. when I change it to the latest version 0.5.1. the error occurred when building

    :/workspace/artipie/src/main/java/com/artipie/SliceFromConfig.java:[51,36] 程序包com.artipie.maven.repository不存在

I think the latest version has removed this class, right?

**Comment by vongosling** [comment]
@yegor256 ping.

**Comment by vongosling** [comment]
Also, I think the ci system passed in the past 8 months. It seems no work since then:-)

**Comment by olegmoz** [comment]
@vongosling 

1. Latest version of `maven-adapter` is in Maven Central, please follow the link: https://search.maven.org/artifact/com.artipie/maven-adapter/0.5.1/jar

2. The error you get is about missing classes, it seems that you try to build the project with some dependency missing. The project can be built with Maven, here are latest build logs from CI: https://github.com/artipie/artipie/actions/runs/278537800

CI pipeline runs for every commit on into master branch and for every PR, we are using GitHub Actions for that, please see: https://github.com/artipie/artipie/actions

**Comment by vongosling** [comment]
@olegmoz I am not sure I expressed the problem clearly. In your master, your dependency is 0.4.10, when I change to the latest version 0.5.1. Error occurred. I just wonder do you remove this class from the latest dependency? I could not build a successful code from the scratch. IMO, it's not a nice experience for a newbie :-)

**Comment by vongosling** [comment]
I success when I change to 0.4.6. IMO, you should check your ci system why it could pass?

**Comment by olegmoz** [comment]
@vongosling please check connectivity on machine you are using for build and/or try to clear local cache. `maven-adapter` `0.5.1` is available at maven central:
https://repo.maven.apache.org/maven2/com/artipie/maven-adapter/0.5.1/maven-adapter-0.5.1.pom
https://repo.maven.apache.org/maven2/com/artipie/maven-adapter/0.5.1/maven-adapter-0.5.1.jar
These links work for me and in build logs I see the following lines if change dependency to `0.5.1`:
```
Downloading from central: https://repo.maven.apache.org/maven2/com/artipie/maven-adapter/0.5.1/maven-adapter-0.5.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/artipie/maven-adapter/0.5.1/maven-adapter-0.5.1.pom (7.2 kB at 7.1 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/artipie/maven-adapter/0.5.1/maven-adapter-0.5.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/com/artipie/maven-adapter/0.5.1/maven-adapter-0.5.1.jar (64 kB at 130 kB/s)
```

**Comment by olegmoz** [comment]
@vongosling did you manage to build the project? Was it temporary or you still experience problems with downloading `maven-adapter` from Maven Central?

**Comment by vongosling** [comment]
@olegmoz I could download 0.5.1, my question is your default version 0.4.10 is not the correct version, and it reports some class could not found when changing it to 0.5.1

**Comment by vongosling** [comment]
I have found the master has updated this dependency to 0,7 version, there is no error now.

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#646` is not assigned, can't get performer
