### ISSUE TITLE
Upgrade maven and enable proxy test

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#649]
Let's upgrade maven to `0.6` and enable maven proxy IT case.

**Comment by olenagerasimova** [comment]
@genryxy could you please take a look?

**Comment by genryxy** [comment]
@olenagerasimova yeah. This issue is similar to #628

**Comment by olenagerasimova** [comment]
@genryxy oh, sorry, closing as a duplicate

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#649` is not assigned, can't get performer
