### ISSUE TITLE
New releases are not marked with latest tag

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#655]
While the real latest is 0.11.1 is the latest, 0.8.14 is shown as the latest:
![image](https://user-images.githubusercontent.com/16746106/94920869-d09ac280-04bf-11eb-997d-446014ce7c01.png)

**Comment by Sammers21** [comment]
@olegmoz, pay attention to this issue, please.

**Comment by olegmoz** [comment]
@Sammers21 thanks for reporting, that's a major issue

**Comment by Sammers21** [comment]
@olegmoz, if it's a major issue, can you fix it?

**Comment by olegmoz** [comment]
@Sammers21 not sure what to do about it. Rultor creates releases with `pre-release` tag and I am not sure it can be configured. I have changed latest release status to `release` so it is fixed. Not yet sure how to do that automatic

**Comment by Sammers21** [comment]
@olegmoz, I guess if you would push a new tag manually, such an issue would not occur. The latest release will be updated correctly.
