### ISSUE TITLE
Add authentication for nuget IT case

### ISSUE THREAD

**Issue by genryxy** [artipie/artipie#657]
There is problem with adding authentication for nuget IT case. I use such testcontainer `new GenericContainer<>("mcr.microsoft.com/dotnet/sdk:5.0")`
At first, I tried to install nuget to execute command `nuget`. But it wasn't installed. So, I have to execute command with help `dotnet nuget`
The `dotnet nuget` doesn't have ability to pass user credentials as parameters. So, username and password should be written in `NuGet.Config`, but `dotnet nuget` doesn't have flag `--config-file`. The workaround [solution ](https://github.com/NuGet/Home/issues/4879#issuecomment-388595639) didn't work for me.
`NuGet.Config` looks like
```
this.source = "artipie-nuget-test";
 List<String> config = new ArrayList<>();
        config.add("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
        config.add("<configuration>");
        config.add("<packageSources>");
        config.add(String.format("<add key=\"%s\" value=\"%s\"/>", this.source, url));
        config.add("</packageSources>");
        config.add("<config>");
        config.add(String.format("<add key=\"DefaultPushSource\" value=\"%s\"/>", url));
        config.add("</config>");
        user.ifPresent(
            usr -> {
                config.add("<apikeys>");
                config.add(String.format("<add key=\"%s\" value=\"%s\"/>", url, this.source));
                config.add("</apikeys>");
                config.add("<packageSourceCredentials>");
                config.add(String.format("<%s>", this.source));
                config.add(String.format("<add key=\"Username\" value=\"%s\"/>", usr.name()));
                config.add(
                    String.format("<add key=\"ClearTextPassword\" value=\"%s\"/>", usr.password())
                );
                config.add(String.format("</%s>", this.source));
                config.add("</packageSourceCredentials>");
            }
        );
        config.add("</configuration>");
```
Save this file
```
Files.write(
            this.tmp.resolve("NuGet.Config"),
            String.join("", config).getBytes()
        );
```
Command for execution
`this.exec( "dotnet", "nuget", "push", pckg, "--api-key", this.source);`
Also tried to remove `DefaultPushSource` and execute
```
final String uri = "http://host.testcontainers.internal:%d/my-nuget/index.json";
this.exec("dotnet", "nuget", "push", pckg, "--api-key", this.source, "-s", String.format(uri, this.port));
```
I received `401 Unauthorized` (when user credentials were written in config for `ArtipieServer`). It seems that `packageSourceCredentials` weren't taken from `NuGet.Config`. 
Probably there is a way to install `nuget` and pass credentials as params. Or somehow make it with `NuGet.config` file.

**Comment by genryxy** [comment]
@olegmoz could you please take a look

**Comment by olegmoz** [comment]
@genryxy thanks for detailed description, we will investigate it later

**Comment by olenagerasimova** [comment]
This issue is not relevant as all the adapters ITs in Artipie do not use authorization, authorization is tested in the adapter itself.
