### ISSUE TITLE
Extract class to build repo config yaml

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#660]
A lot of tests (all the adapters ITs) classes require repo config yaml to be build. Now code to do that is repeating in each class, let's create another class in the test scope to avoid duplications.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it
