### ISSUE TITLE
Authenticate remote endpoint in Maven proxy

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#668]
Remote URI configured in Maven proxy may require authentication. In order to allow access to repositories protected with username/password we need to make it configurable for Maven proxy and implement support

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#674](https://github.com/artipie/artipie/issues/674) is still not solved.

**Comment by 0pdd** [comment]
@olegmoz the only puzzle [#674](https://github.com/artipie/artipie/issues/674) is solved here.

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#668` is not assigned, can't get performer
