### ISSUE TITLE
NugetITCase.java:88-91: Create constructor in...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#677]
The puzzle `602-02a4b526` from #602 has to be resolved: 

https://github.com/artipie/artipie/blob/fa7957a6f55fd53de2136c349707fcb8c895491c/src/test/java/com/artipie/nuget/NugetITCase.java#L88-L91

The puzzle was created by Alexandr on 09-Oct-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#677` is not assigned, can't get performer
