### ISSUE TITLE
Extension documentation

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#68]
Add documentation how to extend Artipie and create custom module or storage

**Comment by 0crat** [comment]
The job [#68](https://github.com/artipie/artipie/issues/68) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/16bfb1fd-d8ca-428a-b620-2a02415e282b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
not relevant, we have docs for asto and http, and other issues to improve docs
