### ISSUE TITLE
Extract profile for IT cases

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#680]
Let's extract integration tests into separate profile and add separate action for it.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) resigned from [#680](https://github.com/artipie/artipie/issues/680), since the job is not in scope anymore
