### ISSUE TITLE
Create class to compose credentials yaml config

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#690]
Let's create class to build credentials yaml config in test scope to replace multiple repeating places where this config is created.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it
