### ISSUE TITLE
Same cache configuration for proxy adapters

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#693]
Cache for proxies is configured is not configured in same way for Docker and Maven. Format of Maven configuration should be updated to be the same as for Docker

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project
