### ISSUE TITLE
Multiple remotes for Maven proxy repository

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#694]
Only single remote endpoint is supported for Maven proxy repository. Multiple Maven remotes may be supported using grouping slice

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#694` is not assigned, can't get performer
