### ISSUE TITLE
Remove usage of `Identities` and `SliceAuth`

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#700]
These deprecated classes are still used in:
- [x] `AuthAndPermissionsTest`
- [x] `SliceFromConfig`, which requires migration in adapters: https://github.com/artipie/npm-adapter/issues/140 https://github.com/artipie/helm-adapter/issues/72 https://github.com/artipie/rpm-adapter/issues/368
- [ ] `AuthApi` and it's usage in `DashboardSlice` and `ArtipieApi`

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#700` is not assigned, can't get performer
