### ISSUE TITLE
Prepare to extract Artipie API into separate repo

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#713]
Let's think through extracting Artipie API into separate repository, come up with some plan and make necessary preparations.

Steps:
- create new repo 
- copy `api` and `dashboard` packages 
- extract interface from `PathPattern` in the new repo
- copy `RepoPermissions` and `Users`, class `RepoPermissions.PermissionItem` to the new repo and step by step get rid of the `artipie` dependency there
- try to add new dependency to artipie and start it, make sure dashboard is working
- get rid of unused modules in the artipie

**Comment by olenagerasimova** [comment]
@olegmoz I've added very exemplary plan here, also at the beginning I wanted to leave `Settings` interface in `artipie` and get rid of this dependency in api slices (requires some coding, but not difficult). But now I see that maybe it would be good to move this interface to the new repo too. What do you think?

**Comment by olegmoz** [comment]
I do not think that whole `Settings` interface deserves to be moved there, it looks like a core class for Artipie. I imagine that this new `management-api` module should  provide just some `Slice` classes for dashboard, REST API etc and interfaces to be implemented. But core functionality like repository APIs should work well without any dependency on new module. Methods like `Settings.auth()` and `Settings.layout()` are used by Artipie core and cannot be moved to some module.

I guess we could move classes like `Settings` and many of your `Yaml<something>` classes to some other module like `config`, but that's another story

**Comment by olenagerasimova** [comment]
@olegmoz then I think we should get rid of `Settings` dependency in api slices, I've created #730

**Comment by g4s8** [comment]
@olenagerasimova can we close this ticket?

**Comment by olenagerasimova** [comment]
@g4s8 yes, thanks
