### ISSUE TITLE
Update python and add proxy

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#714]
Let's update python and add python proxy.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it
