### ISSUE TITLE
Do not throw IOExceptions in Settings

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#729]
Let's remove `IOExceptions` from the methods' signature of `Settings` interface. This should be done by passing `YamlSettings` instance of `YamlMapping` instead of the string. Instance of `com.artipie.YamlSettings` is created in `com/artipie/VertxMain.java:184` from configuration file, we can create `YamlMapping` right there.

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#729` is not assigned, can't get performer
