### ISSUE TITLE
Artipie API slices should not depend on Settings

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#730]
Let's make Artipie API do not depend on `Settings` interface. These slices will be moved to a separate repository, and should not depend on artipie `Settings`. 
Note that interfaces `RepoPermissions` and `Users`, class `RepoPermissions.PermissionItem` will be moved to the new repo along with these slices.

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#790](https://github.com/artipie/artipie/issues/790) is still not solved.
