### ISSUE TITLE
No error message if repository file was not found

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#74]
Artipie just returns 500 error without any message if repository file was not found or directory doesn't exist. Let's return 404 message with text that `repository %s was not found`

**Comment by 0crat** [comment]
The job [#74](https://github.com/artipie/artipie/issues/74) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/5c468195-f4f2-43b1-b221-2ee2a2525365); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by HDouss** [comment]
@g4s8 I am not sure what is asked here. Here's what I tried: starting artipie with a valid config file, the config file has a storage with an invalid folder. When I try to get http://localhost/maven/ I got: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: repos\maven.yaml (along with a stacktrace). Isn't that enough? Do you mind explaining a more precise scenario?

**Comment by HDouss** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@HDouss sorry, I was very clear: we need to return 404 error if user is trying to use not existing repository, not 500 error. E.g. I started Docker image with empty config directory, and sent a request to `localhost/repo` and got 500 error

**Comment by HDouss** [comment]
@g4s8 That's not what I understood from description. So what is asked is to return 404 instead of 500 with a custom message, right?

**Comment by g4s8** [comment]
@HDouss yes, I'll update description

**Comment by HDouss** [comment]
@g4s8 Thanks. Please see PR #92 . This is the most elegant way I found without messing with Slices in subsequent projects.

**Comment by 0crat** [comment]
@hdouss[/z](https://www.0crat.com/u/hdouss) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by HDouss** [comment]
@0crat wait

**Comment by 0crat** [comment]
The job [#74](https://github.com/artipie/artipie/issues/74) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/dd6fc952-234c-49f8-974e-6158d1852589); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#120](https://github.com/artipie/artipie/issues/120) is still not solved.

**Comment by g4s8** [comment]
Done in #117

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#74](https://github.com/artipie/artipie/issues/74), since the job is not in scope anymore

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@47be01ee-43c3-4083-893b-28d1d64d4ea7, thread: PQ-CT2E6TK9B
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [reason, priority, job, cause, _parent_sig, flow, voluntarily, login]
```

[0.53.14](https://github.com/zerocracy/farm): CID: [174d95da-a347-43c3-a5fd-c8ac173adee0](https://www.0crat.com/footprint/CT2E6TK9B/174d95da-a347-43c3-a5fd-c8ac173adee0), Type: "Order was canceled"

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#120](https://github.com/artipie/artipie/issues/120) is solved here.
