### ISSUE TITLE
Fix missing VOLUME declaration

### ISSUE THREAD

**Issue by iaroslavscript** [artipie/artipie#740]
Dockerfile should have VOLUME declaration for persistent data storage and config file as it told in [best-practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#volume).

Please see my pull request #741 

P.S. I had to move config file from `/etc/artipie.yml` to `/etc/artipie/artipie.yml` because it's almost impossible to declare volume as a file and not as directory.

P.P.S. Related to #75

**Comment by olegmoz** [comment]
@rultor release, tag=`0.12.1`

**Comment by olegmoz** [comment]
@iaroslavscript new release is ready and available on DockerHub: https://hub.docker.com/layers/artipie/artipie/0.12.1/images/sha256-b62852a1cfff890e706adc290aecdebda6fab605154856c205c306bcfadbaeaa?context=explore

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#740` is not assigned, can't get performer
