### ISSUE TITLE
Docker image should use volume for store config file

### ISSUE THREAD

**Issue by brastak** [artipie/artipie#75]
Docker image should provide a way for config file to be persistent. Usually it is achieved with copying pre-defined config to the volume path on the first run

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by brastak** [comment]
non-relevant, global repo config can be stored inside container

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#75` is not assigned, can't get performer
