### ISSUE TITLE
RPM repository

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#76]
Add RPM repository HTTP API.

**Comment by 0crat** [comment]
The job [#76](https://github.com/artipie/artipie/issues/76) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/a1b68a52-471a-4c27-9d55-f1f25365c840); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#90](https://github.com/artipie/artipie/issues/90) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#109](https://github.com/artipie/artipie/issues/109), [#110](https://github.com/artipie/artipie/issues/110) are still not solved; solved: [#90](https://github.com/artipie/artipie/issues/90).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#110](https://github.com/artipie/artipie/issues/110) is still not solved; solved: [#109](https://github.com/artipie/artipie/issues/109), [#90](https://github.com/artipie/artipie/issues/90).

**Comment by 0pdd** [comment]
@g4s8 all 3 puzzles are solved here: [#109](https://github.com/artipie/artipie/issues/109), [#110](https://github.com/artipie/artipie/issues/110), [#90](https://github.com/artipie/artipie/issues/90).
