### ISSUE TITLE
Support for debian repositories (deb)

### ISSUE THREAD

**Issue by frittentheke** [artipie/artipie#769]
Since rpm repos are already implemented, it would be nice to also add support for deb / debian style repositories.

**Comment by olegmoz** [comment]
@frittentheke thanks for the request, we are planning to start implementing Debian repository support soon

**Comment by olenagerasimova** [comment]
Several useful links
https://www.debian.org/doc/manuals/repository-howto/repository-howto#setting-up
https://wiki.debian.org/DebianRepository/Format#Debian_Repository_Format

**Comment by g4s8** [comment]
@frittentheke Debian repositories support was implemented and integrated in https://github.com/artipie/artipie/issues/835
