### ISSUE TITLE
Initial IT for Artipie API

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#775]
Let's create minimal test for Artipie API: configure and start Artipie, then send http GET requests to `ArtipieApi` and dashboard and make sure `200 OK` is returned.

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#803](https://github.com/artipie/artipie/issues/803) is still not solved.

**Comment by 0pdd** [comment]
@olenagerasimova the only puzzle [#803](https://github.com/artipie/artipie/issues/803) is solved here.
