### ISSUE TITLE
Increase test coverage for classes that parse yaml files

### ISSUE THREAD

**Issue by genryxy** [artipie/artipie#778]
It would be good to increase test coverage for classes that parse yaml files

- [x] `RepoConfig` (#779 )
- [x]  `StorageAliases.FromYaml` and `RepositioriesFromStorage` (#783 #792)
- [x] `YamlProxyConfig` (#794)

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#778` is not assigned, can't get performer
