### ISSUE TITLE
Feature Request: Support Hex repositories (Erlang / Elixir packages)

### ISSUE THREAD

**Issue by vassilevsky** [artipie/artipie#784]
The only two ways to host private Erlang / Elixir packages right now are:

1. In a private organization at https://hex.pm (for money)
2. In a self-hosted installation of https://github.com/wojtekmach/mini_repo

Both are not ideal:

1. If you host on Hex.pm you risk losing access to the packages (third-party infrastructure)
2. If you have private packages for Java, Ruby, Go, and Elixir, then you have to host a Nexus / Artipie, AND a MiniRepo instance. That's two different things to maintain!

(Our organization does no.2).

It would have been awesome to host everything in one place.

---

Nexus developers don't react to this proposal:

https://issues.sonatype.org/browse/NEXUS-16868

---

Artifactory developers put it on 2021 roadmap:

https://www.jfrog.com/jira/browse/RTFACT-14011

---

Hex format and repository specs:

https://github.com/hexpm/specifications

**Comment by olegmoz** [comment]
@vassilevsky thanks for bringing this up, we didn't consider supporting Hex repositories. We definitely should add support for Hex given there is no support for it in Nexus and Antifactory.

**Comment by vassilevsky** [comment]
Artifactory put it in 2021 roadmap. I've updated the issue description.

**Comment by sergiomacedo** [comment]
Any news on this support?

**Comment by dgarus** [comment]
> Any news on this support?
@sergiomacedo  hi!
We included this issue to our [roadmap](https://github.com/orgs/artipie/projects/3) on the 3 quarter.

**Comment by dgarus** [comment]
@Swizbiz

[artipie/hexpm-adapter](https://github.com/artipie/hexpm-adapter)

**Comment by vassilevsky** [comment]
OMG it is real?!!

**Comment by olenagerasimova** [comment]
@vassilevsky yes, v0.26.0 includes hex pm repository support (it's being released now)
