### ISSUE TITLE
Layout.java:73-75: Add unit tests for Layout.Flat...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#788]
The puzzle `586-ef3e091d` from #586 has to be resolved: 

https://github.com/artipie/artipie/blob/2b62fd5e99b44ff4035c5795ad86e4eb2857bc89/src/main/java/com/artipie/Layout.java#L73-L75

The puzzle was created by @olegmoz on 03-Dec-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `586-ef3e091d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#788](https://github.com/artipie/artipie/issues/788) is not in the agenda of @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), can't set title
