### ISSUE TITLE
Support .yaml and .yml extensions for config files

### ISSUE THREAD

**Issue by genryxy** [artipie/artipie#797]
Now there are can be some problems with parsing yaml files because in various classes there is logic based on the configuration files' extensions. So, it is necessary to find all these places and make support for files with two extensions (`yaml` and `yml`).

**Comment by 0pdd** [comment]
@genryxy the puzzle [#818](https://github.com/artipie/artipie/issues/818) is still not solved.

**Comment by 0pdd** [comment]
@genryxy the only puzzle [#818](https://github.com/artipie/artipie/issues/818) is solved here.
