### ISSUE TITLE
Properly handle invalid repo configs on start

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#804]
On start we read all yaml files in the settings storage and try to create repositories from them. But the settings storage can contain other yaml (for example, default storage configuration of permissions to access dashboard). Now these yamls are named starting with underscore and are files starting with underscore are ignored. This approach does seem correct and convenient, we should figure out the proper way to deal with it and document it.

**Comment by portlek** [comment]
what about using JSON for settings files, and YAML for repository files? Is that a good way to deal with it?
