### ISSUE TITLE
DashboardSlice.java:68-71: When `ContentAs` is used here...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#818]
The puzzle `797-df0b20e0` from #797 has to be resolved: 

https://github.com/artipie/artipie/blob/bf8ee6015a74afcc7fb40ddff2ec1b8997355d83/src/main/java/com/artipie/api/DashboardSlice.java#L68-L71

The puzzle was created by Aleksandr Krasnov on 18-Dec-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by olenagerasimova** [comment]
Invalid, as Dashboard slice was moved to another repo
