### ISSUE TITLE
Helm integration tests failing

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#822]
`com.artipie.helm.HelmITCase.uploadChartAndCreateIndexYaml` test started to fail because of the following error:
```
Error: error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
```

https://kubernetes-charts.storage.googleapis.com/ responds with `403` and the following message:
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.list access to the Google Cloud Storage bucket.</Details></Error>
```

The problem might be temporary (or not?), but it is needed to understand if we may make the test more stable.

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#822` is not assigned, can't get performer
