### ISSUE TITLE
Make output for IT cases more verbose

### ISSUE THREAD

**Issue by genryxy** [artipie/artipie#826]
Now  only command for execution is logged in integration tests. It would be better to make output of these tests more verbose so that the problem can identified in case of failure.

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#826` is not assigned, can't get performer
