### ISSUE TITLE
Tags support in local and proxy Docker

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#829]
Docker adapter has full support of image tags endpoint for local and proxy repositories since version `0.10`. The dependency should be updated in Artipie, so it will have tags support for Docker repositories

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#829` is not assigned, can't get performer
