### ISSUE TITLE
Incorrect and confusing indentation in the documentation

### ISSUE THREAD

**Issue by HDouss** [artipie/artipie#83]
The example given in the documentation of the repo settings for the NPM example gives a confusing permissions example. This is more important as it is the only permissions example in the documentation.
`admin` and the other usernames does not have the same indentation and its child element is 4 spaces away.
I expect the other usernames to be in the same indentation level as `admin` and that every child element will always be 2 space-indented.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by HDouss** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@HDouss thanks, fixed: https://github.com/artipie/artipie/commit/c4c3cd2a258146f0ae149b69930c3dd794945613

**Comment by HDouss** [comment]
@g4s8 we don't have rewards for reporting bugs in this project?

**Comment by g4s8** [comment]
@HDouss this one was too small, such bugs usually are not going to scope, I'd recommend grouping small bugs about documentation, e.g. "These parts of README could be improved: 1) 2) 3)". Please see https://www.zerocracy.com/policy.html#29
> “Pay per Bug.” Each time you report a new bug that becomes a job, you earn +15 minutes. The ARC makes a subjective non-disputable decision whether a reported bug deserves to be a job or not.

**Comment by HDouss** [comment]
@g4s8 Ok. Thanks.

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#83` is not assigned, can't get performer
