### ISSUE TITLE
Compatibility with docker granular permissions

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#832]
Granular permissions are now supported in `docker-adapter`, it is needed to update `docker-adapter` dependency in Artipie. Permissions model is now incompatible, so it will an adapter is required for two permission models

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#832` is not assigned, can't get performer
