### ISSUE TITLE
Add debian-adapter

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#835]
Let's add debian-adapter to Artipie, do not forget about
- proof
- integration test
- example and readme

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) resigned from [#835](https://github.com/artipie/artipie/issues/835), since the job is not in scope anymore
