### ISSUE TITLE
Re-enable binary proof

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#842]
After unrelated changes in https://github.com/artipie/artipie/pull/841 binary proof started to fail. It seems to be some issue with GitHub actions, as the same action with same code changes successfully runs in other repository: https://github.com/olegmoz/artipie/actions/runs/501064796

Seems that there is some issues with actions isolation, such as cache sharing. It needs to be investigated.

**Comment by olenagerasimova** [comment]
done in #845

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#842` is not assigned, can't get performer
