### ISSUE TITLE
Fix docker release

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#851]
Fix docker image releasing

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#855](https://github.com/artipie/artipie/issues/855) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.16`

**Comment by 0pdd** [comment]
@g4s8 5 puzzles [#855](https://github.com/artipie/artipie/issues/855), [#860](https://github.com/artipie/artipie/issues/860), [#861](https://github.com/artipie/artipie/issues/861), [#862](https://github.com/artipie/artipie/issues/862), [#863](https://github.com/artipie/artipie/issues/863) are still not solved.

**Comment by 0pdd** [comment]
@g4s8 4 puzzles [#855](https://github.com/artipie/artipie/issues/855), [#861](https://github.com/artipie/artipie/issues/861), [#862](https://github.com/artipie/artipie/issues/862), [#863](https://github.com/artipie/artipie/issues/863) are still not solved; solved: [#860](https://github.com/artipie/artipie/issues/860).

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#855](https://github.com/artipie/artipie/issues/855), [#861](https://github.com/artipie/artipie/issues/861), [#863](https://github.com/artipie/artipie/issues/863) are still not solved; solved: [#860](https://github.com/artipie/artipie/issues/860), [#862](https://github.com/artipie/artipie/issues/862).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#861](https://github.com/artipie/artipie/issues/861), [#977](https://github.com/artipie/artipie/issues/977) are still not solved; solved: [#855](https://github.com/artipie/artipie/issues/855), [#860](https://github.com/artipie/artipie/issues/860), [#862](https://github.com/artipie/artipie/issues/862), [#863](https://github.com/artipie/artipie/issues/863).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#861](https://github.com/artipie/artipie/issues/861), [#996](https://github.com/artipie/artipie/issues/996) are still not solved; solved: [#855](https://github.com/artipie/artipie/issues/855), [#860](https://github.com/artipie/artipie/issues/860), [#862](https://github.com/artipie/artipie/issues/862), [#863](https://github.com/artipie/artipie/issues/863), [#977](https://github.com/artipie/artipie/issues/977).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#1013](https://github.com/artipie/artipie/issues/1013), [#861](https://github.com/artipie/artipie/issues/861) are still not solved; solved: [#855](https://github.com/artipie/artipie/issues/855), [#860](https://github.com/artipie/artipie/issues/860), [#862](https://github.com/artipie/artipie/issues/862), [#863](https://github.com/artipie/artipie/issues/863), [#977](https://github.com/artipie/artipie/issues/977), [#996](https://github.com/artipie/artipie/issues/996).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#861](https://github.com/artipie/artipie/issues/861) is still not solved; solved: [#1013](https://github.com/artipie/artipie/issues/1013), [#855](https://github.com/artipie/artipie/issues/855), [#860](https://github.com/artipie/artipie/issues/860), [#862](https://github.com/artipie/artipie/issues/862), [#863](https://github.com/artipie/artipie/issues/863), [#977](https://github.com/artipie/artipie/issues/977), [#996](https://github.com/artipie/artipie/issues/996).
