### ISSUE TITLE
Unnecessary operations on each request

### ISSUE THREAD

**Issue by HDouss** [artipie/artipie#87]
On every request received by artipie (when using the default Pie slice), we do the following operations:
* retrieve storage from settings, which reads the yaml content (does not read the file again, but the file content as read at the first time) for "meta -> storage" entry.
* get the value of this storage scalar.

This is corresponding to that code:
```java
CompletableFuture.supplyAsync(
    () -> new Unchecked<>(this.settings::storage).value()
)
```

These two operations are redundant because they will always have the same result, there is no need to make it at every received request.
Ideally, if we won't support hot changing repos config files, we could implement a sort of cache that will return the whole slice (that is decorated by the AsyncSlice) based on the repo. Every repo is associated to a single slice, there is no need to recalculate that at every request. By "the whole slice that is decorated by the AsyncSlice", I meant this part of the code:
```java
CompletableFuture.supplyAsync(
    () -> new Unchecked<>(this.settings::storage).value()
)
.thenComposeAsync(
    storage -> storage.value(new Key.From(String.format("%s.yaml", repo)))
)
.thenApply(content -> new RepoConfig(content))
.thenCompose(Pie::sliceForConfig)

```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@HDouss actually we want to support configuration changes, e.g. if you add new repository config, the server should handle this repository on next request. But it would be a good idea to cache configuration for some time, e.g. 5 minutes

**Comment by HDouss** [comment]
@g4s8 Even if we want that, there are redundant operations (even if they are small), retrieving storage from the settings reparses the yaml stored content.

**Comment by g4s8** [comment]
@HDouss but it may be changed, what if you decide to move repository storage from local file system to S3 storage? Then config will be updated and should be parsed again

**Comment by HDouss** [comment]
@g4s8 these operations I am talking about are not about a single repository config but about artipie config, the one with meta. These are not hot-changeable because the file content is stored in `YamlSettings` as a string, but the parsing happens in every request (see `YamlSettings.storage` method)

**Comment by g4s8** [comment]
@HDouss got it, then it's a valid improvement

**Comment by 0crat** [comment]
The job [#87](https://github.com/artipie/artipie/issues/87) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/496e296f-dc61-4c08-8fd7-e6cd1e9da4d2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.
