### ISSUE TITLE
Absence of Pypi in Repository types dropdown

### ISSUE THREAD

**Issue by zuoqin** [artipie/artipie#872]
1. Create new pypi configuration:
```
zuoqin@zuoqin:/var/artipie/repo/artipie$ ls -l
total 4
-rwxrwxrwx 1 2020 2021 71 Mar 17 10:15 pypi.yml
```
2. Run artipie docker: `docker run  --name artipie -v /var/artipie:/var/artipie -p 8080:8080 --user=artipie:artipie artie/artipie:0.17.1`
3. Absence of Pypi:

![image](https://user-images.githubusercontent.com/9687716/111617876-bdbd4580-87f4-11eb-8c67-8ca8264e1cc3.png)

**Comment by genryxy** [comment]
@g4s8 this issue was closed as not valid now

![image](https://user-images.githubusercontent.com/38591972/128493158-b7a9c48c-6d4b-4c48-b844-d0175a657d44.png)
