### ISSUE TITLE
Monitoring and metrics tool

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#889]
Add monitoring support for Artipie. Now all metrics are collected into the log, let's add additional metrics provider, like https://github.com/prometheus/prometheus

**Comment by g4s8** [comment]
@milkysoft I'd recommend starting with investigation of the correct metric's collecting way in our case. E.g. what are the pros and cons of push vs pull strategy, and what method is more suitable in our case for Artipie.

Please read this:
 - https://prometheus.io/docs/practices/pushing/
 - https://github.com/prometheus/pushgateway/blob/master/README.md

**Comment by milkysoft** [comment]
PushGateway vs Promethus pooling

1. PushGateway is state of the art service, complete compatible with load balancers, [kubernetes](https://hub.kubeapps.com/charts/prometheus-community/prometheus-pushgateway/1.4.0) etc, which allows to split pushed metrics among instances according to specific requirements
2.

**Comment by g4s8** [comment]
@baudoliver7 are you familiar with [prometheus](https://github.com/prometheus/prometheus), do you have some experience with it?

**Comment by baudoliver7** [comment]
@g4s8 I have no experience with it. However, nothing prevents me from investigating if you don't mind :)

**Comment by baudoliver7** [comment]
> @milkysoft I'd recommend starting with investigation of the correct metric's collecting way in our case. E.g. what are the pros and cons of push vs pull strategy, and what method is more suitable in our case for Artipie.
> 
> Please read this:
> 
> * https://prometheus.io/docs/practices/pushing/
> * https://github.com/prometheus/pushgateway/blob/master/README.md

@g4s8 After investigating, I think pull strategy is more suitable in our case to avoid `Prometheus` to miss some metrics in case `Pushgateway` jobs failed. And I notice that when jobs fail, they stay in this state until we debug and restore them. We've got also other pitfalls described in this quote :

> `Pushgateway` is used in certain limited cases because it has several pitfalls :
> - When monitoring multiple instances through a single `Pushgateway,` the `Pushgateway` becomes both a single point of failure and a potential bottleneck.
> - You lose Prometheus's automatic instance health monitoring via the up metric (generated on every scrape).
> - The Pushgateway never forgets series pushed to it and will expose them to Prometheus forever unless those series are manually deleted via the Pushgateway's API.

**Comment by g4s8** [comment]
@baudoliver7 yes, agree, let's use pull strategy.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#978](https://github.com/artipie/artipie/issues/978) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#980](https://github.com/artipie/artipie/issues/980) is still not solved; solved: [#978](https://github.com/artipie/artipie/issues/978).
