### ISSUE TITLE
Push php/composer as zip

### ISSUE THREAD

**Issue by icukeng** [artipie/artipie#895]
According to examples artipie store php package separated on two pieces: zip in bin repo and package information in php repo. One need to configure two repos and to make two push requests.
Composer adapter seems to implement pushing one-piece as zip archive (https://github.com/artipie/composer-adapter/issues/23). But I can't trigger it.

Maybe this functionality does not implemented properly or disabled for some point, but it will be great to creating such functionality/

**Comment by g4s8** [comment]
@icukeng thanks for reporting. @genryxy I think we need to add a template in the dashboard for Composer, similar to other repositories like Maven, etc
