### ISSUE TITLE
Pie.java:111-113: Extract the logic in switch into...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#90]
The puzzle `76-fe362791` from #76 has to be resolved: 

https://github.com/artipie/artipie/blob/95e04444ef222129f0e3dfdde67fb65ee884bcf6/src/main/java/com/artipie/Pie.java#L111-L113

The puzzle was created by @g4s8 on 22-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The job [#90](https://github.com/artipie/artipie/issues/90) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/2ad88dba-5acf-459f-a316-02435cb3b637); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `76-fe362791` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#109](https://github.com/artipie/artipie/issues/109), [#110](https://github.com/artipie/artipie/issues/110) are still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@0pdd the puzzle [#110](https://github.com/artipie/artipie/issues/110) is still not solved; solved: [#109](https://github.com/artipie/artipie/issues/109).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#109](https://github.com/artipie/artipie/issues/109), [#110](https://github.com/artipie/artipie/issues/110).
