### ISSUE TITLE
Add PushGateway for Prometheus metrics

### ISSUE THREAD

**Issue by milkysoft** [artipie/artipie#906]
Add monitoring support for Artipie. Now all metrics are collected into the log, let's add additional metrics provider, like https://github.com/prometheus/prometheus. PushGateway pushed metrics to [Prometheus](https://prometheus.zhedge.xyz/graph?g0.expr=metric1_total&g0.tab=0&g0.stacked=0&g0.range_input=1h)

**Comment by g4s8** [comment]
@milkysoft closing as a copy-paste of #889 ticket
