### ISSUE TITLE
add container to docker registry with "latest" tag

### ISSUE THREAD

**Issue by artemlazarev** [artipie/artipie#91]
In the documentation we have description with container "latest". but at the dockerhub that container are absent.

**Comment by g4s8** [comment]
@artemlazarev right, let's tag the same image with latest as well as with release tag

**Comment by artemlazarev** [comment]
@g4s8 It's Time to close this issue as resolved?

**Comment by g4s8** [comment]
@artemlazarev sure, you can close this ticket if it's solved. We're using this workflow for closing:
 1. Author reports a ticket with problem or improvement
 2. Performer fixes this problem and notifies ticket reporter
 3. Author verifies that the problem was solved and closes the ticket

**Comment by artemlazarev** [comment]
solved

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#91` is not assigned, can't get performer
