### ISSUE TITLE
Using the Conventional commits specification

### ISSUE THREAD

**Issue by eugenelesnov** [artipie/artipie#919]
According to [Conventional commits summary](https://www.conventionalcommits.org/en/v1.0.0/) : 

The Conventional Commits specification is a lightweight convention on top of commit messages. It provides an easy set of rules for creating an explicit commit history; which makes it easier to write automated tools on top of.

**Comment by g4s8** [comment]
@artipie/members what do you think (see the link above)?

**Comment by genryxy** [comment]
@g4s8 looks good as it would simplify understanding which version should be released after making changes. And in general, it does not impose many restrictions on the commit format

**Comment by EugeneLesnov** [comment]
I'm glad you liked this idea. Such approach can be annoying (meh) for developers at first, but the result will definitely be worth the effort.
