### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Manish7992** [artipie/artipie#957]
As I have created a docker repo in which I'll give the permission to the user to "Upload and Download" . But that user still not able to upload the image

**Comment by g4s8** [comment]
@Manish7992 can you provide more details please? E.g. configuration files, command you are using to start Docker, etc

**Comment by g4s8** [comment]
@genryxy can you please check this issue?

**Comment by genryxy** [comment]
@g4s8 after adding mentioned lines it works properly. It could be closed or stay open in order to wait response from asker
