### ISSUE TITLE
in the "maven.yml", running maven on compilation target "ubuntu-latest" is unnecessary

### ISSUE THREAD

**Issue by artemlazarev** [artipie/artipie#96]
in the "maven.yml:9" running maven on compilation target "ubuntu-latest" is unnecessary.
Because we  build docker image at the "ubuntu-latest"  host.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#96` is not assigned, can't get performer
