### ISSUE TITLE
API Cannot get list of users and create/update user

### ISSUE THREAD

**Issue by OrlovM** [artipie/artipie#965]
I'm running artipie inside Docker, with a command:
`docker run --rm -v /etc/artipie:/etc/artipie -v /var/artipie:/var/artipie --name artipie -p 8080:8080 artipie/artipie:latest`

Most API calls works as intended.
But there is a problem with users.
I can only get or delete existing user.

If I try to get list of users with:
`curl -u artipie:artipie -v http://localhost:8080/api/security/users`
It responds with 403 status code.

And artipie crashes when I try to use `PUT` or `POST` method e.g.:
`curl -u artipie:artipie -X 'PUT' -d '{"password":"plain:test","email":"test@test.com"}' http://localhost:8080/api/security/users/test
`
Output of artipie is attached.

[artipie.txt](https://github.com/artipie/artipie/files/7505381/artipie.txt)

**Comment by olenagerasimova** [comment]
@OrlovM hi,
1) there is a separate file with permissions to access Artipie api, it's yaml config called `_permissions.yaml`, check the example [here](https://github.com/artipie/artipie/blob/master/src/main/resources/example/repo/_permissions.yaml). Is the file present in your configuration? As for corresponding documentation, I do not see any, guess we have to add it later 
2) there is no need to pass password type, it's `plain` by default, please, try `{"password":"test","email":"test@test.com"}`

**Comment by OrlovM** [comment]
@olenagerasimova hi!

1. Yes, I've copied config files from [example](https://github.com/artipie/artipie/tree/master/src/main/resources/example) dir of artipie. I have an `artipie.yaml` file located inside /etc/artipie and all other config files inside /var/artipie/repo.
2. I have the same result with different variations of JSON data and `PUT` or `POST` requests to `/security/users/{username}`.

**Comment by olenagerasimova** [comment]
This API not valid anymore, see https://github.com/artipie/front
