### ISSUE TITLE
add additional java version to maven build process

### ISSUE THREAD

**Issue by artemlazarev** [artipie/artipie#97]
At this moment we have only java 11 in the maven build action. We think it will be good to add java 13.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#97](https://github.com/artipie/artipie/issues/97) assigned to @artemlazarev[/z](https://www.0crat.com/u/artemlazarev), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/c36191ea-23b6-4f74-a252-8f8f3643a13a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @artemlazarev[/z](https://www.0crat.com/u/artemlazarev) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@artemlazarev[/z](https://www.0crat.com/u/artemlazarev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by artemlazarev** [comment]
@g4s8 It's Time to close this issue as resolved?

**Comment by artemlazarev** [comment]
solved

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#97` is not assigned, can't get performer
