### ISSUE TITLE
API calls to repositories does not work as intended.

### ISSUE THREAD

**Issue by OrlovM** [artipie/artipie#972]
I'm running artipie inside Docker, with a command:
`docker run --rm -v /etc/artipie:/etc/artipie -v /var/artipie:/var/artipie --name artipie -p 8080:8080 artipie/artipie:latest`

There are some problems with repositories:

First of all, it is not mentioned in any of the docs, endpoint to access repositories is not `api/repositories`, but `api/repos`. I had to look up inside artipie code to investigate it. Get request to `api/repositories` responds with 404 statuscode.

Response of `curl -u artipie:artipie http://localhost:8080/api/repos/artipie` is JSON of this kind:
`{    
    "user": "artipie",
    "repositories": [
        "artipie/123",
        "artipie/asd",
        "artipie/binary",
        "artipie/test"
    ]
}`
I thought it should return more information about repositories, like Artifactory does.

I don't know if it made intentionally, `GET` request to `api/repos/artipie/<repo_name>` responds with repository `yaml` configuration file, instead of expected JSON data.

After all, it is impossible to create or modify a repository:
`PUT` and `POST` requests to `api/repos/artipie/repoKey` responds with 404 code.
And same requests to `api/repositories/artipie/repoKey` results to artipie crash with BlockedThread exception.

[artipie.txt](https://github.com/artipie/artipie/files/7576981/artipie.txt)

**Comment by olenagerasimova** [comment]
This API not valid anymore, see https://github.com/artipie/front
