### ISSUE TITLE
PromuSlice.java:30-34: Test that {@link PromuSlice}'s...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#978]
The puzzle `889-be863331` from #889 has to be resolved: 

https://github.com/artipie/artipie/blob/90c304bb9075bd02e5ca97ecfcb078b90ee4ba79/src/main/java/com/artipie/http/PromuSlice.java#L30-L34

The puzzle was created by @baudoliver7 on 15-Dec-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by baudoliver7** [comment]
@g4s8 could you assign me this please ?

**Comment by baudoliver7** [comment]
@g4s8 could you assign me this please ?

**Comment by 0pdd** [comment]
@0pdd the puzzle [#980](https://github.com/artipie/artipie/issues/980) is still not solved.
