### ISSUE TITLE
PromuSliceTest.java:40-42: Add an IT test for PromuSlice....

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#980]
The puzzle `978-28850aee` from #978 has to be resolved: 

https://github.com/artipie/artipie/blob/c1913c2ba120324968c7faa68af7ab867b3262bf/src/test/java/com/artipie/http/PromuSliceTest.java#L40-L42

The puzzle was created by Olivier B. OURA on 24-Dec-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by baudoliver7** [comment]
@g4s8 assign me this task, please.

**Comment by baudoliver7** [comment]
@g4s8 Thx :)
Resolved in PR #982

**Comment by 0pdd** [comment]
The puzzle `978-28850aee` has disappeared from the source code, that's why I closed this issue.
