### ISSUE TITLE
Fix reports and smoke tests - ci

### ISSUE THREAD

**Issue by baudoliver7** [artipie/artipie#983]
All PRs submitted have failed status because these two workflows (Reports and Smoke tests) always fail. We should fix them.

**Comment by baudoliver7** [comment]
@g4s8 please, assign

**Comment by g4s8** [comment]
@baudoliver7 thanks, removed codecov action in https://github.com/artipie/artipie/commit/7f9f53b75c7446e0dbb5280eab83b648af671a95

For smoke-tests we already have a ticket #847
