### ISSUE TITLE
Restructure Artipie components

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#988]
Currently, it seems we have some "reactive overhead" in Artipie module for Dashboard and API - these components are not good candidates for applying reactive streams on them, because:
  1) API and Dashboard data traffic is very low and request frequency is rare, comparing to repository traffic.
  2) almost all requests contains only one chunk of data, so using `Publisher` of `ByteBuffer` for processing one `ByteBuffer` is overhead
  3) using non-blocking reactive streams approach requires a lot of additional code and work, which is OK if we pay it for better performance or resources consumption for high-load traffic, but in case with Dashboard and API, the traffic is low.

## Proposal

I'm suggesting restructure Dashboard and API code and move it to separate software components (dedicated servers). It allows us to:
 - Simplify the code in `artipie/artipie` module by removing the code related to API management and Dashboard.
 - Use other approaches (maybe another web frameworks or even languages) for other modules.
 - Simplify changes in Dashboard and API, since these changes will not depend on main Artipie components (makes coupling lower).
 - Better (granular) resources control for these components in big applications in cluster.

Possibly, API and dashboard could be one component, not two.

## Implementation

Dashboard and API components may expose endpoints for `/api` and `/dashboard` URL paths; primary load-balancer routes requests based on this path: `/api` paths goes to API service, `/dashboard` path to Dashboard service and other requests to main Artipie service (see diagram below).

![artipie-component drawio](https://user-images.githubusercontent.com/1524988/150475027-6f8b968e-2e1b-4d9f-bb4c-8c3b5da9b71f.png)

## Questions

Using this approach, some aspects are not clear:
 1) How to provide simple deployment for local usage (now we have Docker with Dashboard and API included). Maybe Docker-compose or something like this can be used for that (if users needs dashboard and API for tiny local deployments).
 2) Auth mechanism for API and Dashboard - now it's rely on `artipie/http` authorization implementation, we may need to copy-paste this logic if we switch to multiservice components.

**Comment by g4s8** [comment]
@artipie/members what is your opinion here?

**Comment by g4s8** [comment]
Related issues:
 - https://github.com/artipie/artipie/issues/972
 - https://github.com/artipie/artipie/issues/965
 - https://github.com/artipie/artipie/issues/923
 - https://github.com/artipie/artipie/issues/464
 - https://github.com/artipie/artipie/issues/357
 - https://github.com/artipie/artipie/issues/352
 - https://github.com/artipie/artipie/issues/317
 - https://github.com/artipie/artipie/issues/287
 - https://github.com/artipie/artipie/issues/256

**Comment by olenagerasimova** [comment]
@g4s8 generally, I think that's a good idea. Also, here is a question: are we going to keep API as is? It was created based on artifactory API (or even to support the same endpoint as artifactory does) and sometimes does correspond artipie architecture. So maybe it will make sense to review/remake it somehow

**Comment by g4s8** [comment]
> @g4s8 generally, I think that's a good idea. Also, here is a question: are we going to keep API as is? It was created based on artifactory API (or even to support the same endpoint as artifactory does) and sometimes does correspond artipie architecture. So maybe it will make sense to review/remake it somehow

I think we can create new API for Artipie focused on managing Artipie configuration resources, e.g.:

**Comment by ChGen** [comment]
I think splitting on separate components makes sense and is a good moment to consider API changes.

**Comment by g4s8** [comment]
@artipie/members what do you think about this framework for API service? https://sparkjava.com/

**Comment by ChGen** [comment]
Looks quite cute :)

**Comment by g4s8** [comment]
> @g4s8 yes, looks interesting, though meanwhile I did not find any information about how to create unit test for the endpoints.

@olenagerasimova https://sparkjava.com/tutorials/unit-testing

**Comment by olenagerasimova** [comment]
@g4s8 thanks, spark looks even now

**Comment by g4s8** [comment]
@artipie/maintainers created new repo and ticket: https://github.com/artipie/front/issues/1

**Comment by dgarus** [comment]
@g4s8 @olenagerasimova @ChGen 
The experience of using Artipie without API showed that this approach is not convenient and essentially complicate server's deployment. Moreover, in some cases it's impossible to use the service and API due to API should have the same main configuration and accordingly has the same permissions as server to get access to data host.
Furthermore, this approach requires extra efforts to extend UI (phone, CLI, wed using another framework and so on).
So, the best way is to have one point to get/change main configuration by common API.

Let's close this issue.

**Comment by olenagerasimova** [comment]
@dgarus let's close, I do not mind

**Comment by ChGen** [comment]
@dgarus , Ok.
